# Form implementation generated from reading ui file 'ui/DD_ViewImage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
import os
import sys
from PyQt6.QtGui import QPixmap
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.dirname(SCRIPT_DIR))
from BUS.DiemDanhBUS import DiemDanhBUS

class DD_ViewImage(object):
    idDD = ''
    def __init__(self , id):
        self.idDD = id
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 300)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 300))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        self.getImage()
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Ảnh điểm danh"))
        self.label.setText(_translate("Form", "TextLabel"))
    
    def getImage(self):
        ddBUS = DiemDanhBUS()
        list = ddBUS.findMaDiemDanh(self.idDD)
        if list is not None:
            for row in list:
                link_image = row[0]
        pixmap = QPixmap(link_image)
        pixmap = pixmap.scaled(300, 300, Qt.AspectRatioMode.KeepAspectRatio)
        self.label.setPixmap(pixmap)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = DD_ViewImage()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
