# Form implementation generated from reading ui file 'ui/DialogListChucNang.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os
import sys
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.dirname(SCRIPT_DIR))
from BUS.ChucNangBUS import ChucNangBUS
from DAL.ChucNang import ChucNang
from BUS.Quyen_ChucNangBUS import Quyen_ChucNangBUS
from DAL.Quyen_ChucNang import Quyen_ChucNang

class Ui_Dialog(object):
        list_ckb_cn = []
        listcnmacdinh = []
        maquyen = ""
        def __init__(self, maquyen):
            self.maquyen = maquyen
        def setupUi(self, Dialog):
            Dialog.setObjectName("Dialog")
            Dialog.resize(240, 320)
            self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
            self.buttonBox.setGeometry(QtCore.QRect(10, 270, 221, 41))
            self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
            self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
            self.buttonBox.setObjectName("buttonBox")
            self.label = QtWidgets.QLabel(parent=Dialog)
            self.label.setGeometry(QtCore.QRect(0, 10, 241, 41))
            font = QtGui.QFont()
            font.setPointSize(11)
            font.setBold(True)
            font.setWeight(75)
            self.label.setFont(font)
            self.label.setStyleSheet("#label\n"
    "{\n"
    "font-weight: bold;\n"
    "}")
            self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            self.label.setObjectName("label")
            self.listWidget = QtWidgets.QListWidget(parent=Dialog)
            self.listWidget.setGeometry(QtCore.QRect(20, 50, 200, 211))
            self.listWidget.setObjectName("listWidget")

            self.openDialogListChucNang(self.maquyen)
            self.retranslateUi(Dialog)
            self.buttonBox.accepted.connect(Dialog.accept)                
            self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
            QtCore.QMetaObject.connectSlotsByName(Dialog)

        def retranslateUi(self, Dialog):
            _translate = QtCore.QCoreApplication.translate
            Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
            self.label.setText(_translate("Dialog", "DANH SÁCH CHỨC NĂNG"))


        def openDialogListChucNang(self, maquyen):    
            self.list_ckb_cn.clear()
            qcn = Quyen_ChucNangBUS()
            listqcn = qcn.getListChucNangTheoQuyen(maquyen)

            cn = ChucNangBUS()
            list = cn.get()      
            for cn in list:
                ckb = QtWidgets.QCheckBox(self.listWidget)
                ckb.setText(cn[1])
                ckb.setObjectName(cn[0]) 
                # KIỂM TRA CHỨC NĂNG CÓ SẴN
                if cn[0] in listqcn:
                    ckb.setChecked(True)
                self.list_ckb_cn.append(ckb)

                self.newitem = QtWidgets.QListWidgetItem()
                self.newitem.setSizeHint(QtCore.QSize(0,40))      

                self.listWidget.addItem(self.newitem)
                self.listWidget.setItemWidget(self.newitem,ckb)
            
        def getListChucNangChecked(self):            
            listcncheck= []
            for ckb in self.list_ckb_cn:
                if ckb.isChecked():
                    listcncheck.append(ckb.objectName())
            return listcncheck
                
            

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog('Q001')
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
