# Form implementation generated from reading ui file 'ui/QuanLySinhVien.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QMessageBox
import os
import sys
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.dirname(SCRIPT_DIR))
from BUS.face_training import face_training
from DAL.ConnectDatabase import ConnectDatabase

from BUS.SinhVienBUS import SinhVienBUS
from DAL.SinhVien import SinhVien
from CameraLayAnh import CameraLayAnh
from ViewImage import ViewImage
from datetime import datetime
from BUS.LopBUS import LopBUS
from DAL.Lop import Lop
from check_error import check_error

class UI_QuanLySinhVien(object):
        ma = ""
        maL = ""

        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(800, 590)
                self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.frmHeader = QtWidgets.QFrame(parent=self.centralwidget)
                self.frmHeader.setGeometry(QtCore.QRect(0, 30, 851, 51))
                self.frmHeader.setAccessibleName("")
                self.frmHeader.setLayoutDirection(
                        QtCore.Qt.LayoutDirection.LeftToRight)
                self.frmHeader.setStyleSheet("#frmHeader{background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255))}\n"
                "")
                self.frmHeader.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
                self.frmHeader.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
                self.frmHeader.setLineWidth(1)
                self.frmHeader.setObjectName("frmHeader")
                self.label_3 = QtWidgets.QLabel(parent=self.frmHeader)
                self.label_3.setGeometry(QtCore.QRect(0, 0, 801, 51))
                font = QtGui.QFont()
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.label_3.setFont(font)
                self.label_3.setStyleSheet("#label_3\n"
                "{\n"
                "    font-weight:bold;\n"
                "}")
                self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                self.label_3.setObjectName("label_3")
                self.btnBack = QtWidgets.QPushButton(parent=self.frmHeader)
                self.btnBack.setGeometry(QtCore.QRect(730, 12, 61, 23))
                self.btnBack.setCursor(QtGui.QCursor(
                        QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnBack.setObjectName("btnBack")
                self.label_2 = QtWidgets.QLabel(parent=self.frmHeader)
                self.label_2.setGeometry(QtCore.QRect(50, 10, 91, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setStyleStrategy(QtGui.QFont.StyleStrategy.NoAntialias)
                self.label_2.setFont(font)
                self.label_2.setAcceptDrops(False)
                self.label_2.setToolTip("")
                self.label_2.setAutoFillBackground(False)
                self.label_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
                self.label_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
                self.label_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
                self.label_2.setScaledContents(False)
                self.label_2.setWordWrap(False)
                self.label_2.setIndent(-1)
                self.label_2.setTextInteractionFlags(
                        QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
                self.label_2.setObjectName("label_2")
                self.label_4 = QtWidgets.QLabel(parent=self.frmHeader)
                self.label_4.setGeometry(QtCore.QRect(50, 30, 91, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label_4.setFont(font)
                self.label_4.setObjectName("label_4")
                self.btnDark = QtWidgets.QPushButton(parent=self.frmHeader)
                self.btnDark.setGeometry(QtCore.QRect(680, 8, 31, 31))
                self.btnDark.setCursor(QtGui.QCursor(
                        QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnDark.setText("")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("ui\\../image/icon/moon_symbol_50px.png"),
                                QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.btnDark.setIcon(icon)
                self.btnDark.setIconSize(QtCore.QSize(20, 20))
                self.btnDark.setObjectName("btnDark")
                self.btnTime = QtWidgets.QPushButton(parent=self.frmHeader)
                self.btnTime.setGeometry(QtCore.QRect(10, 10, 31, 31))
                self.btnTime.setCursor(QtGui.QCursor(
                        QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnTime.setStyleSheet("#btnTime\n"
                "{\n"
                "background-color: transparent;\n"
                "}")
                self.btnTime.setText("")
                icon1 = QtGui.QIcon()
                icon1.addPixmap(QtGui.QPixmap("ui\\image/icon/time_50px.png"),
                                QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.btnTime.setIcon(icon1)
                self.btnTime.setIconSize(QtCore.QSize(20, 20))
                self.btnTime.setObjectName("btnTime")
                self.label_3.raise_()
                self.btnBack.raise_()
                self.label_4.raise_()
                self.label_2.raise_()
                self.btnDark.raise_()
                self.btnTime.raise_()
                
                self.frame_6 = QtWidgets.QFrame(parent=self.centralwidget)
                self.frame_6.setGeometry(QtCore.QRect(0, 0, 801, 31))
                self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
                self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
                self.frame_6.setObjectName("frame_6")
                self.btnClose = QtWidgets.QPushButton(parent=self.frame_6)
                self.btnClose.setGeometry(QtCore.QRect(777, 4, 24, 24))
                self.btnClose.setCursor(QtGui.QCursor(
                        QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnClose.setText("")
                icon2 = QtGui.QIcon()
                icon2.addPixmap(QtGui.QPixmap("ui\\../image/icon/close_50px.png"),
                                QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.btnClose.setIcon(icon2)
                self.btnClose.setIconSize(QtCore.QSize(20, 20))
                self.btnClose.setObjectName("btnClose")
                self.btnMinimize = QtWidgets.QPushButton(parent=self.frame_6)
                self.btnMinimize.setGeometry(QtCore.QRect(752, 4, 24, 24))
                self.btnMinimize.setCursor(QtGui.QCursor(
                        QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnMinimize.setText("")
                icon3 = QtGui.QIcon()
                icon3.addPixmap(QtGui.QPixmap("ui\\../image/icon/subtract_50px.png"),
                                QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.btnMinimize.setIcon(icon3)
                self.btnMinimize.setIconSize(QtCore.QSize(20, 20))
                self.btnMinimize.setObjectName("btnMinimize")
                self.label_20 = QtWidgets.QLabel(parent=self.frame_6)
                self.label_20.setGeometry(QtCore.QRect(10, 2, 201, 26))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setStyleStrategy(QtGui.QFont.StyleStrategy.NoAntialias)
                self.label_20.setFont(font)
                self.label_20.setAcceptDrops(False)
                self.label_20.setToolTip("")
                self.label_20.setAutoFillBackground(False)
                self.label_20.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
                self.label_20.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
                self.label_20.setTextFormat(QtCore.Qt.TextFormat.AutoText)
                self.label_20.setScaledContents(False)
                self.label_20.setWordWrap(False)
                self.label_20.setIndent(-1)
                self.label_20.setTextInteractionFlags(
                        QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
                self.label_20.setObjectName("label_20")
                self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
                self.layoutWidget.setGeometry(QtCore.QRect(20, 100, 761, 471))
                self.layoutWidget.setObjectName("layoutWidget")
                self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
                self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.frmChangeSV = QtWidgets.QFrame(parent=self.layoutWidget)
                self.frmChangeSV.setStyleSheet("#frmChangeSV\n"
                "{\n"
                "    border-width: 2;\n"
                "    border-radius: 5;\n"
                "     border-style: solid;\n"
                "      border-color: #457fca;\n"
                "}")
                self.frmChangeSV.setFrameShape(QtWidgets.QFrame.Shape.Box)
                self.frmChangeSV.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
                self.frmChangeSV.setLineWidth(2)
                self.frmChangeSV.setMidLineWidth(0)
                self.frmChangeSV.setObjectName("frmChangeSV")
                self.frame = QtWidgets.QFrame(parent=self.frmChangeSV)
                self.frame.setGeometry(QtCore.QRect(20, 10, 341, 91))
                self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
                self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
                self.frame.setObjectName("frame")
                self.label_5 = QtWidgets.QLabel(parent=self.frame)
                self.label_5.setGeometry(QtCore.QRect(10, 13, 131, 21))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_5.setFont(font)
                self.label_5.setStyleSheet("#label_5\n"
                "{\n"
                "font-weight: bold;\n"
                "}")
                self.label_5.setObjectName("label_5")


                self.label_7 = QtWidgets.QLabel(parent=self.frame)
                self.label_7.setGeometry(QtCore.QRect(10, 50, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_7.setFont(font)
                #self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom |
                #                                QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_7.setObjectName("label_7")
                # self.cmbKhoaHoc = QtWidgets.QLineEdit(parent=self.frame)
                # self.cmbKhoaHoc.setGeometry(QtCore.QRect(70, 50, 121, 21))
                # font = QtGui.QFont()
                # font.setPointSize(9)
                # self.cmbKhoaHoc.setFont(font)
                # self.cmbKhoaHoc.setObjectName("cmbKhoaHoc")
                self.cmbKhoaHoc = QtWidgets.QDateEdit(parent=self.frame)
                self.cmbKhoaHoc.setGeometry(QtCore.QRect(70, 50, 121, 21))
                self.cmbKhoaHoc.setDisplayFormat("yyyy")
                self.cmbKhoaHoc.setObjectName("cmbKhoaHoc")

                self.frame_2 = QtWidgets.QFrame(parent=self.frmChangeSV)
                self.frame_2.setGeometry(QtCore.QRect(20, 110, 341, 251))
                self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
                self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
                self.frame_2.setObjectName("frame_2")
                self.label_8 = QtWidgets.QLabel(parent=self.frame_2)
                self.label_8.setGeometry(QtCore.QRect(10, 16, 141, 21))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_8.setFont(font)
                self.label_8.setStyleSheet("#label_8\n"
                "{\n"
                "font-weight: bold;\n"
                "}")
                self.label_8.setObjectName("label_8")
                self.label_10 = QtWidgets.QLabel(parent=self.frame_2)
                self.label_10.setGeometry(QtCore.QRect(10, 50, 51, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_10.setFont(font)
                self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom |
                                                QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_10.setObjectName("label_10")
                self.txtHoTen = QtWidgets.QLineEdit(parent=self.frame_2)
                self.txtHoTen.setGeometry(QtCore.QRect(65, 50, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.txtHoTen.setFont(font)
                self.txtHoTen.setText("")
                self.txtHoTen.setObjectName("txtHoTen")
                self.label_11 = QtWidgets.QLabel(parent=self.frame_2)
                self.label_11.setGeometry(QtCore.QRect(180, 50, 51, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_11.setFont(font)
                self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom |
                                                QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_11.setObjectName("label_11")

                self.cmbLop = QtWidgets.QComboBox(parent=self.frame_2)
                self.cmbLop.setGeometry(QtCore.QRect(230, 50, 101, 21))
                self.cmbLop.setObjectName("cmbLop")
                self.cmbLop.addItem("","")
                self.label_12 = QtWidgets.QLabel(parent=self.frame_2)
                self.label_12.setGeometry(QtCore.QRect(170, 100, 51, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_12.setFont(font)
                self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom |
                                                QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_12.setObjectName("label_12")
                self.txtCMND = QtWidgets.QLineEdit(parent=self.frame_2)
                self.txtCMND.setGeometry(QtCore.QRect(230, 100, 101, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.txtCMND.setFont(font)
                self.txtCMND.setText("")
                self.txtCMND.setObjectName("txtCMND")
                self.label_13 = QtWidgets.QLabel(parent=self.frame_2)
                self.label_13.setGeometry(QtCore.QRect(10, 150, 51, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_13.setFont(font)
                self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom |
                                                QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_13.setObjectName("label_13")

                self.cmbGioiTinh = QtWidgets.QComboBox(parent=self.frame_2)
                self.cmbGioiTinh.setGeometry(QtCore.QRect(65, 150, 91, 21))
                self.cmbGioiTinh.setObjectName("cmbGioiTinh")
                self.cmbGioiTinh.addItem("Nam","Nam")
                self.cmbGioiTinh.addItem("Nữ","Nữ")


                self.label_14 = QtWidgets.QLabel(parent=self.frame_2)
                self.label_14.setGeometry(QtCore.QRect(10, 100, 61, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_14.setFont(font)
                self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom |
                                                QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_14.setObjectName("label_14")

                self.dateNgaySinh = QtWidgets.QDateEdit(parent=self.frame_2)
                self.dateNgaySinh.setGeometry(QtCore.QRect(65, 100, 91, 21))
                self.dateNgaySinh.setDisplayFormat("yyyy-MM-dd")
                self.dateNgaySinh.setObjectName("dateNgaySinh")

                self.label_15 = QtWidgets.QLabel(parent=self.frame_2)
                self.label_15.setGeometry(QtCore.QRect(10, 200, 51, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_15.setFont(font)
                self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom |
                                                QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_15.setObjectName("label_15")
                self.txtEmail = QtWidgets.QLineEdit(parent=self.frame_2)
                self.txtEmail.setGeometry(QtCore.QRect(65, 200, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.txtEmail.setFont(font)
                self.txtEmail.setText("")
                self.txtEmail.setObjectName("txtEmail")
                self.label_16 = QtWidgets.QLabel(parent=self.frame_2)
                self.label_16.setGeometry(QtCore.QRect(170, 150, 51, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_16.setFont(font)
                self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom |
                                                QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_16.setObjectName("label_16")
                self.txtSDT = QtWidgets.QLineEdit(parent=self.frame_2)
                self.txtSDT.setGeometry(QtCore.QRect(230, 150, 101, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.txtSDT.setFont(font)
                self.txtSDT.setText("")
                self.txtSDT.setObjectName("txtSDT")               
                self.horizontalLayoutWidget = QtWidgets.QWidget(
                        parent=self.frmChangeSV)
                self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 370, 341, 51))
                self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(
                        self.horizontalLayoutWidget)
                self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.btnThemSV = QtWidgets.QPushButton(
                        parent=self.horizontalLayoutWidget)
                self.btnThemSV.setCursor(QtGui.QCursor(
                        QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnThemSV.setStyleSheet("#btnThemSV{\n"
                "background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "color:white;\n"
                "font-weight:bold;\n"
                "border-radius:3px;\n"
                "padding: 5px;\n"
                "}\n"
                "#btnThemSV:hover{\n"
                "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "}")
                self.btnThemSV.setObjectName("btnThemSV")
                self.btnThemSV.clicked.connect(self.add)
                self.horizontalLayout_2.addWidget(self.btnThemSV)
                self.btnSuaSV = QtWidgets.QPushButton(
                        parent=self.horizontalLayoutWidget)
                self.btnSuaSV.setCursor(QtGui.QCursor(
                        QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnSuaSV.setStyleSheet("#btnSuaSV{\n"
                "background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "color:white;\n"
                "font-weight:bold;\n"
                "border-radius:3px;\n"
                "padding: 5px;\n"
                "}\n"
                "#btnSuaSV:hover{\n"
                "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "}")
                self.btnSuaSV.setObjectName("btnSuaSV")
                self.btnSuaSV.clicked.connect(self.update)
                self.horizontalLayout_2.addWidget(self.btnSuaSV)
                self.btnXoaSV = QtWidgets.QPushButton(
                        parent=self.horizontalLayoutWidget)
                self.btnXoaSV.setCursor(QtGui.QCursor(
                        QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnXoaSV.setStyleSheet("#btnXoaSV{\n"
                "background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "color:white;\n"
                "font-weight:bold;\n"
                "border-radius:3px;\n"
                "padding: 5px;\n"
                "}\n"
                "#btnXoaSV:hover{\n"
                "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "}")
                self.btnXoaSV.setObjectName("btnXoaSV")
                self.btnXoaSV.clicked.connect(self.delete)
                self.horizontalLayout_2.addWidget(self.btnXoaSV)
                self.btnLamMoiSV = QtWidgets.QPushButton(
                        parent=self.horizontalLayoutWidget)
                self.btnLamMoiSV.setCursor(QtGui.QCursor(
                        QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnLamMoiSV.setStyleSheet("#btnLamMoiSV{\n"
                "background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "color:white;\n"
                "font-weight:bold;\n"
                "border-radius:3px;\n"
                "padding: 5px;\n"
                "}\n"
                "#btnLamMoiSV:hover{\n"
                "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "}")
                self.btnLamMoiSV.setObjectName("btnLamMoiSV")
                self.btnLamMoiSV.clicked.connect(self.clear)
                self.horizontalLayout_2.addWidget(self.btnLamMoiSV)
                self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.frmChangeSV)
                self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 420, 341, 41))
                self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
                self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
                self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_3.setObjectName("horizontalLayout_3")

                self.btnLayAnhSV = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
                self.btnLayAnhSV.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnLayAnhSV.clicked.connect(self.show_camera)
                self.btnLayAnhSV.setStyleSheet("#btnLayAnhSV{\n"
                "background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "color:white;\n"
                "font-weight:bold;\n"
                "border-radius:3px;\n"
                "padding: 5px;\n"
                "}\n"
                "#btnLayAnhSV:hover{\n"
                "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "}")
                self.btnLayAnhSV.setObjectName("btnLayAnhSV")
                self.horizontalLayout_3.addWidget(self.btnLayAnhSV)

                self.btnTrainImage = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
                self.btnTrainImage.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnTrainImage.setStyleSheet("#btnTrainImage{\n"
                "background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "color:white;\n"
                "font-weight:bold;\n"
                "border-radius:3px;\n"
                "padding: 5px;\n"
                "}\n"
                "#btnTrainImage:hover{\n"
                "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "}")
                self.btnTrainImage.setObjectName("btnTrainImage")
                self.btnTrainImage.clicked.connect(self.trainImage)
                self.horizontalLayout_3.addWidget(self.btnTrainImage)

                self.btnXemAnhSV = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
                self.btnXemAnhSV.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnXemAnhSV.clicked.connect(self.show_image)
                self.btnXemAnhSV.setStyleSheet("#btnXemAnhSV{\n"
                "background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "color:white;\n"
                "font-weight:bold;\n"
                "border-radius:3px;\n"
                "padding: 5px;\n"
                "}\n"
                "#btnXemAnhSV:hover{\n"
                "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "}")
                self.btnXemAnhSV.setObjectName("btnXemAnhSV")
                self.horizontalLayout_3.addWidget(self.btnXemAnhSV)
                self.horizontalLayout.addWidget(self.frmChangeSV)
                self.frmMain_2 = QtWidgets.QFrame(parent=self.layoutWidget)
                self.frmMain_2.setStyleSheet("#frmMain\n"
                "{\n"
                "    border-width: 1;\n"
                "    border-radius: 5;\n"
                "     border-style: solid;\n"
                "      border-color: #457fca;\n"
                "}")
                self.frmMain_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
                self.frmMain_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
                self.frmMain_2.setLineWidth(2)
                self.frmMain_2.setObjectName("frmMain_2")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.frmMain_2)
                self.verticalLayout.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout.setObjectName("verticalLayout")
                self.frmInfoSV = QtWidgets.QFrame(parent=self.frmMain_2)
                self.frmInfoSV.setStyleSheet("#frmInfoSV\n"
                "{\n"
                "    border-width: 2;\n"
                "    border-radius: 5;\n"
                "     border-style: solid;\n"
                "      border-color: #457fca;\n"
                "}")
                self.frmInfoSV.setFrameShape(QtWidgets.QFrame.Shape.Box)
                self.frmInfoSV.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
                self.frmInfoSV.setLineWidth(2)
                self.frmInfoSV.setObjectName("frmInfoSV")
                self.frame_3 = QtWidgets.QFrame(parent=self.frmInfoSV)
                self.frame_3.setGeometry(QtCore.QRect(10, 10, 361, 71))
                self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.Box)
                self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
                self.frame_3.setObjectName("frame_3")
                self.label_17 = QtWidgets.QLabel(parent=self.frame_3)
                self.label_17.setGeometry(QtCore.QRect(10, 14, 131, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_17.setFont(font)
                self.label_17.setObjectName("label_17")
                self.label_18 = QtWidgets.QLabel(parent=self.frame_3)
                self.label_18.setGeometry(QtCore.QRect(10, 40, 101, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_18.setFont(font)
                self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom |
                                                QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_18.setObjectName("label_18")
                self.cmbOptionFindSV = QtWidgets.QComboBox(parent=self.frame_3)
                self.cmbOptionFindSV.setGeometry(QtCore.QRect(110, 40, 81, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.cmbOptionFindSV.setFont(font)
                self.cmbOptionFindSV.setObjectName("cmbOptionFindSV")
                self.cmbOptionFindSV.addItem("Mã SV", "masinhvien")
                self.cmbOptionFindSV.addItem("Họ tên", "hoten")
                self.cmbOptionFindSV.addItem("Mã lớp", "malop")
                self.cmbOptionFindSV.addItem("CMND", "cmnd")
                self.cmbOptionFindSV.addItem("Giới tính", "gioitinh")
                self.cmbOptionFindSV.addItem("Email", "email")
                self.cmbOptionFindSV.addItem("Số điện thoại", "sodienthoai")
                self.cmbOptionFindSV.addItem("Khóa học", "khoahoc")
                self.cmbOptionFindSV.currentIndexChanged.connect(self.find)

                self. txtFindSV = QtWidgets.QLineEdit(parent=self.frame_3)
                self.txtFindSV.setGeometry(QtCore.QRect(200, 40, 151, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.txtFindSV.setFont(font)
                self.txtFindSV.setText("")
                self.txtFindSV.textChanged.connect(self.find)
                self.txtFindSV.setObjectName("txtFindSV")

                self.tbwSV = QtWidgets.QTableWidget(parent=self.frmInfoSV)
                self.tbwSV.setGeometry(QtCore.QRect(10, 90, 361, 131))
                self.tbwSV.setObjectName("tbwSV")
                self.tbwSV.setColumnCount(9)
                self.tbwSV.setRowCount(2)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setVerticalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setVerticalHeaderItem(1, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setHorizontalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setHorizontalHeaderItem(1, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setHorizontalHeaderItem(2, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setHorizontalHeaderItem(3, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setHorizontalHeaderItem(4, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setHorizontalHeaderItem(5, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setHorizontalHeaderItem(6, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setHorizontalHeaderItem(7, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setHorizontalHeaderItem(8, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setItem(0, 0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setItem(0, 1, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setItem(0, 2, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setItem(0, 3, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setItem(0, 4, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setItem(0, 5, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setItem(0, 6, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setItem(0, 7, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setItem(0, 8, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setItem(1, 0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwSV.setItem(1, 1, item)
                self.tbwSV.itemClicked.connect(self.getDataRow)
                self.tbwSV.setEditTriggers(QtWidgets.QTableWidget.EditTrigger.NoEditTriggers)
                self.loadDataQTable()
                self.verticalLayout.addWidget(self.frmInfoSV)
                self.frmClass = QtWidgets.QFrame(parent=self.frmMain_2)
                self.frmClass.setStyleSheet("#frmClass\n"
                "{\n"
                "    border-width: 2;\n"
                "    border-radius: 5;\n"
                "     border-style: solid;\n"
                "      border-color: #457fca;\n"
                "}")


                # Quản lý lớp học

                self.frmClass.setFrameShape(QtWidgets.QFrame.Shape.Box)
                self.frmClass.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
                self.frmClass.setLineWidth(2)
                self.frmClass.setObjectName("frmClass")
                self.label_19 = QtWidgets.QLabel(parent=self.frmClass)
                self.label_19.setGeometry(QtCore.QRect(110, 0, 181, 41))
                font = QtGui.QFont()
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.label_19.setFont(font)
                self.label_19.setStyleSheet("#label_19\n"
                "{\n"
                "    font-weight:bold;\n"
                "}")
                self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                self.label_19.setObjectName("label_19")
                self.frame_4 = QtWidgets.QFrame(parent=self.frmClass)
                self.frame_4.setGeometry(QtCore.QRect(10, 40, 361, 41))
                self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.Box)
                self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
                self.frame_4.setObjectName("frame_4")
                self.label_21 = QtWidgets.QLabel(parent=self.frame_4)
                self.label_21.setGeometry(QtCore.QRect(10, 10, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_21.setFont(font)
                self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom |
                                                QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_21.setObjectName("label_21")

                self.cmbOptionFindLop = QtWidgets.QComboBox(parent=self.frame_4)
                self.cmbOptionFindLop.setGeometry(QtCore.QRect(110, 10, 81, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.cmbOptionFindLop.setFont(font)
                self.cmbOptionFindLop.currentIndexChanged.connect(self.findLop)
                self.cmbOptionFindLop.setObjectName("cmbOptionFindLop")
                self.cmbOptionFindLop.addItem("Mã lớp", "malop")
                self.cmbOptionFindLop.addItem("Tên lớp", "tenlop")

                self.txtFindLop = QtWidgets.QLineEdit(parent=self.frame_4)
                self.txtFindLop.setGeometry(QtCore.QRect(200, 10, 151, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.txtFindLop.setFont(font)
                self.txtFindLop.setText("")
                self.txtFindLop.textChanged.connect(self.findLop)
                self.txtFindLop.setObjectName("txtFindLop")
                

                self.label_22 = QtWidgets.QLabel(parent=self.frmClass)
                self.label_22.setGeometry(QtCore.QRect(20, 116, 51, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_22.setFont(font)
                self.label_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom |
                                                QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_22.setObjectName("label_22")
                self.txtLop2 = QtWidgets.QLineEdit(parent=self.frmClass)
                self.txtLop2.setGeometry(QtCore.QRect(60, 116, 111, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.txtLop2.setFont(font)
                self.txtLop2.setText("")
                self.txtLop2.setObjectName("txtLop")
                self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=self.frmClass)
                self.horizontalLayoutWidget_4.setGeometry(
                        QtCore.QRect(20, 190, 151, 31))
                self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
                self.horizontalLayout_5 = QtWidgets.QHBoxLayout(
                        self.horizontalLayoutWidget_4)
                self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_5.setObjectName("horizontalLayout_5")
                self.btnXoaLop = QtWidgets.QPushButton(
                        parent=self.horizontalLayoutWidget_4)
                self.btnXoaLop.setCursor(QtGui.QCursor(
                        QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnXoaLop.setStyleSheet("#btnXoaLop{\n"
                "background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "color:white;\n"
                "font-weight:bold;\n"
                "border-radius:3px;\n"
                "padding: 5px;\n"
                "}\n"
                "#btnXoaLop:hover{\n"
                "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "}")
                self.btnXoaLop.setObjectName("btnXoaLop")
                self.btnXoaLop.clicked.connect(self.deleteLop)
                self.horizontalLayout_5.addWidget(self.btnXoaLop)
                self.btnLamMoiLop = QtWidgets.QPushButton(
                        parent=self.horizontalLayoutWidget_4)
                self.btnLamMoiLop.setCursor(QtGui.QCursor(
                        QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnLamMoiLop.setStyleSheet("#btnLamMoiLop{\n"
                "background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "color:white;\n"
                "font-weight:bold;\n"
                "border-radius:3px;\n"
                "padding: 5px;\n"
                "}\n"
                "#btnLamMoiLop:hover{\n"
                "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "}")
                self.btnLamMoiLop.setObjectName("btnLamMoiLop")
                self.btnLamMoiLop.clicked.connect(self.clearLop)
                self.horizontalLayout_5.addWidget(self.btnLamMoiLop)
                self.tbwLop = QtWidgets.QTableWidget(parent=self.frmClass)
                self.tbwLop.setGeometry(QtCore.QRect(180, 90, 191, 131))
                self.tbwLop.setObjectName("tbwLop")
                self.tbwLop.setColumnCount(2)
                self.tbwLop.setRowCount(4)
                item = QtWidgets.QTableWidgetItem()
                self.tbwLop.setVerticalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwLop.setVerticalHeaderItem(1, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwLop.setVerticalHeaderItem(2, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwLop.setVerticalHeaderItem(3, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwLop.setHorizontalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwLop.setHorizontalHeaderItem(1, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwLop.setItem(0, 0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwLop.setItem(0, 1, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwLop.setItem(1, 0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwLop.setItem(1, 1, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwLop.setItem(2, 0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwLop.setItem(2, 1, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwLop.setItem(3, 0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwLop.setItem(3, 1, item)
                self.tbwLop.itemClicked.connect(self.getDataRowLop)
                self.loadDataQTableLop()
                self.horizontalLayoutWidget_5 = QtWidgets.QWidget(parent=self.frmClass)
                self.horizontalLayoutWidget_5.setGeometry(
                        QtCore.QRect(20, 160, 151, 31))
                self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
                self.horizontalLayout_6 = QtWidgets.QHBoxLayout(
                        self.horizontalLayoutWidget_5)
                self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_6.setObjectName("horizontalLayout_6")
                self.btnThemLop = QtWidgets.QPushButton(
                        parent=self.horizontalLayoutWidget_5)
                self.btnThemLop.setCursor(QtGui.QCursor(
                        QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnThemLop.setStyleSheet("#btnThemLop{\n"
                "background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "color:white;\n"
                "font-weight:bold;\n"
                "border-radius:3px;\n"
                "padding: 5px;\n"
                "}\n"
                "#btnThemLop:hover{\n"
                "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "}")
                self.btnThemLop.setObjectName("btnThemLop")
                self.btnThemLop.clicked.connect(self.addLop)
                self.horizontalLayout_6.addWidget(self.btnThemLop)
                self.btnSuaLop = QtWidgets.QPushButton(
                        parent=self.horizontalLayoutWidget_5)
                self.btnSuaLop.setCursor(QtGui.QCursor(
                        QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnSuaLop.setStyleSheet("#btnSuaLop{\n"
                "background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "color:white;\n"
                "font-weight:bold;\n"
                "border-radius:3px;\n"
                "padding: 5px;\n"
                "}\n"
                "#btnSuaLop:hover{\n"
                "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
                "}")
                self.btnSuaLop.setObjectName("btnSuaLop")
                self.btnSuaLop.clicked.connect(self.updateLop)
                self.horizontalLayout_6.addWidget(self.btnSuaLop)
                self.verticalLayout.addWidget(self.frmClass)
                self.horizontalLayout.addWidget(self.frmMain_2)
                MainWindow.setCentralWidget(self.centralwidget)

                self.loadDataCmbLop()
                self.retranslateUi(MainWindow)
                # tạo timer
                self.timer = QtCore.QTimer()
                self.timer.timeout.connect(self.clock_number)
                # start and update every second
                self.timer.start(1000)
                self.clock_number()
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label_3.setText(_translate("MainWindow", "Quản lý sinh viên"))
                self.btnBack.setText(_translate("MainWindow", "Trở về"))
                self.label_20.setText(_translate("MainWindow", "Phần mềm điểm danh sinh viên"))
                self.label_5.setText(_translate("MainWindow", "Thông tin khóa học:"))
                self.label_7.setText(_translate("MainWindow", "Khóa học:"))
                self.label_8.setText(_translate("MainWindow", "Thông tin sinh viên:"))
                self.label_10.setText(_translate("MainWindow", "Họ tên:"))
                self.label_11.setText(_translate("MainWindow", "Lớp"))
                self.label_12.setText(_translate("MainWindow", "CMND"))
                self.label_13.setText(_translate("MainWindow", "Giới tính"))
                self.label_14.setText(_translate("MainWindow", "Ngày sinh"))
                self.label_15.setText(_translate("MainWindow", "Email"))
                self.label_16.setText(_translate("MainWindow", "SĐT"))
                self.btnThemSV.setText(_translate("MainWindow", "Thêm"))
                self.btnSuaSV.setText(_translate("MainWindow", "Sửa"))
                self.btnXoaSV.setText(_translate("MainWindow", "Xóa"))
                self.btnLamMoiSV.setText(_translate("MainWindow", "Làm mới"))
                self.btnLayAnhSV.setText(_translate("MainWindow", "Lấy ảnh sinh viên"))
                self.btnXemAnhSV.setText(_translate("MainWindow", "Xem ảnh"))
                self.btnTrainImage.setText(_translate("MainWindow", "Train ảnh"))
                self.label_17.setText(_translate("MainWindow", "Hệ thống tìm kiếm:"))
                self.label_18.setText(_translate("MainWindow", "Tìm kiếm theo:"))
                self.cmbOptionFindSV.setItemText(0, _translate("MainWindow", "Mã SV"))
                item = self.tbwSV.verticalHeaderItem(0)
                item.setText(_translate("MainWindow", "1"))
                item = self.tbwSV.verticalHeaderItem(1)
                item.setText(_translate("MainWindow", "2"))
                item = self.tbwSV.horizontalHeaderItem(0)
                item.setText(_translate("MainWindow", "Mã SV"))
                item = self.tbwSV.horizontalHeaderItem(1)
                item.setText(_translate("MainWindow", "Họ tên"))
                item = self.tbwSV.horizontalHeaderItem(2)
                item.setText(_translate("MainWindow", "Lớp"))
                item = self.tbwSV.horizontalHeaderItem(3)
                item.setText(_translate("MainWindow", "CMND"))
                item = self.tbwSV.horizontalHeaderItem(4)
                item.setText(_translate("MainWindow", "Giới tính"))
                item = self.tbwSV.horizontalHeaderItem(5)
                item.setText(_translate("MainWindow", "Ngày sinh"))
                item = self.tbwSV.horizontalHeaderItem(6)
                item.setText(_translate("MainWindow", "Email"))
                item = self.tbwSV.horizontalHeaderItem(7)
                item.setText(_translate("MainWindow", "Số điện thoại"))
                item = self.tbwSV.horizontalHeaderItem(8)
                item.setText(_translate("MainWindow", "Khoá học"))
                __sortingEnabled = self.tbwSV.isSortingEnabled()
                self.tbwSV.setSortingEnabled(__sortingEnabled)
                

                # Quản lý lớp học

                
                self.label_19.setText(_translate("MainWindow", "Quản lý lớp học"))
                self.label_21.setText(_translate("MainWindow", "Tìm kiếm theo:"))
                self.label_22.setText(_translate("MainWindow", "Lớp:"))
                self.btnXoaLop.setText(_translate("MainWindow", "Xóa"))
                self.btnLamMoiLop.setText(_translate("MainWindow", "Làm mới"))
                item = self.tbwLop.horizontalHeaderItem(0)
                item.setText(_translate("MainWindow", "Mã lớp"))
                item = self.tbwLop.horizontalHeaderItem(1)
                item.setText(_translate("MainWindow", "Lớp"))
                __sortingEnabled = self.tbwLop.isSortingEnabled()
                self.tbwLop.setSortingEnabled(False)
                
                self.tbwLop.setSortingEnabled(__sortingEnabled)
                self.btnThemLop.setText(_translate("MainWindow", "Thêm"))
                self.btnSuaLop.setText(_translate("MainWindow", "Sửa"))


        def loadDataQTable(self):

                sv = SinhVienBUS()
                list = sv.get()
                tablerow = 0
                self.tbwSV.setRowCount(list.__len__())
                if list is not None:
                        for row in list:
                                self.tbwSV.setItem(
                                tablerow, 0, QtWidgets.QTableWidgetItem(str(row[0])))
                                self.tbwSV.setItem(
                                tablerow, 1, QtWidgets.QTableWidgetItem(str(row[1])))
                                self.tbwSV.setItem(
                                tablerow, 2, QtWidgets.QTableWidgetItem(str(row[2])))
                                self.tbwSV.setItem(
                                tablerow, 3, QtWidgets.QTableWidgetItem(str(row[3])))
                                self.tbwSV.setItem(
                                tablerow, 4, QtWidgets.QTableWidgetItem(str(row[4])))
                                self.tbwSV.setItem(
                                tablerow, 5, QtWidgets.QTableWidgetItem(str(row[5])))
                                self.tbwSV.setItem(
                                tablerow, 6, QtWidgets.QTableWidgetItem(str(row[6])))
                                self.tbwSV.setItem(
                                tablerow, 7, QtWidgets.QTableWidgetItem("0"+str(row[7])))
                                self.tbwSV.setItem(
                                tablerow, 8, QtWidgets.QTableWidgetItem(str(row[8])))
                                tablerow += 1

        def loadDataCmbLop(self):
                lopBUS = LopBUS()
                list = lopBUS.get()
                if list is not None:
                        for row in list:
                                self.cmbLop.addItem(row[1],row[0])


        def getDataRow(self):
                cr = self.tbwSV.currentRow()
                self.ma = self.tbwSV.item(cr, 0).text()
                self.txtHoTen.setText(self.tbwSV.item(cr, 1).text())
                self.cmbLop.setCurrentIndex(self.cmbLop.findData(self.tbwSV.item(cr, 2).text()))

                self.txtCMND.setText(self.tbwSV.item(cr, 3).text())
                self.cmbGioiTinh.setCurrentText(self.tbwSV.item(cr, 4).text())

                date_str = self.tbwSV.item(cr,5).text()
                date_format = "%Y-%m-%d"
                date = datetime.strptime(date_str,date_format).date()
                self.dateNgaySinh.setDate(date)

                self.txtEmail.setText(self.tbwSV.item(cr, 6).text())
                self.txtSDT.setText(self.tbwSV.item(cr, 7).text())

                year_str = self.tbwSV.item(cr,8).text()
                year_format = "%Y"
                year = datetime.strptime(year_str,year_format).date()
                self.cmbKhoaHoc.setDate(year)


        def clear(self):
                self.txtHoTen.clear()
                self.cmbLop.setCurrentIndex(0)
                self.txtCMND.clear()
                self.cmbGioiTinh.setCurrentIndex(0)
                self.dateNgaySinh.clear()
                self.txtEmail.clear()
                self.txtSDT.clear()
                self.cmbKhoaHoc.clear()

        def validateSV(self, sv: SinhVien):        
                if sv._hoten == '' or sv._malop == '' or \
                sv._cmnd == '' or sv._sodienthoai == '' or sv._email == '':
                        QMessageBox.information(self.centralwidget,"Thông báo","Vui lòng nhập đầy đủ thông tin")
                        return False
                if check_error.check_email(self, input=sv._email) == False:
                        QMessageBox.information(self.centralwidget,"Thông báo","Vui lòng nhập email đúng định dạng")
                        return False
                if check_error.check_cmnd(self, input=sv._cmnd) == False:
                        QMessageBox.information(self.centralwidget,"Thông báo","Vui lòng nhập CMND đúng định dạng")
                        return False
                if check_error.check_phone(self, input=sv._sodienthoai) == False:
                        QMessageBox.information(self.centralwidget,"Thông báo","Vui lòng nhập số điện thoại đúng định dạng")
                        return False
                if SinhVienBUS.checkTonTai(self, key="cmnd", value=sv._cmnd) == False:
                        QMessageBox.information(self.centralwidget,"Thông báo","CMND đã tồn tại")
                        return False
                if SinhVienBUS.checkTonTai(self, key="sodienthoai", value=sv._sodienthoai) == False:
                        QMessageBox.information(self.centralwidget,"Thông báo","Số điện thoại đã tồn tại")
                        return False
                if SinhVienBUS.checkTonTai(self, key="email", value=sv._email) == False:
                        QMessageBox.information(self.centralwidget,"Thông báo","Email đã tồn tại")
                        return False
                return True


        def add(self):
                svBUS = SinhVienBUS()
                masinhvien = svBUS.generateID()
                hoten = self.txtHoTen.text()
                malop = self.cmbLop.currentData()
                cmnd = self.txtCMND.text()
                gioitinh = self.cmbGioiTinh.currentData()
                date = self.dateNgaySinh.text()
                email = self.txtEmail.text()
                sodienthoai = self.txtSDT.text()
                khoahoc = self.cmbKhoaHoc.text()
                
                sv = SinhVien(masinhvien, hoten, malop , cmnd, gioitinh, date, email ,sodienthoai, khoahoc)
                if self.validateSV(sv):             
                        if(svBUS.add(sv)):
                                QMessageBox.information(self.centralwidget,"Thông báo","Thêm thành công")
                                self.loadDataQTable()
                                self.clear()
                        else:
                                QMessageBox.information(self.centralwidget,"Thông báo","Thêm thất bại")

        def update(self):
                svBUS = SinhVienBUS()
                masinhvien = self.ma
                hoten = self.txtHoTen.text()
                malop = self.cmbLop.currentData()
                cmnd = self.txtCMND.text()
                gioitinh = self.cmbGioiTinh.currentData()
                date = self.dateNgaySinh.text()
                email = self.txtEmail.text()
                sodienthoai = self.txtSDT.text()
                khoahoc = self.cmbKhoaHoc.text()
                sv = SinhVien(masinhvien, hoten, malop , cmnd, gioitinh, date,email ,sodienthoai,khoahoc)
                if self.validateSV(sv):    
                        if(svBUS.update(sv)):
                                QMessageBox.information(self.centralwidget,"Thông báo","Cập nhật thành công")
                                self.loadDataQTable()
                        else:
                                QMessageBox.information(self.centralwidget,"Thông báo","Cập nhật thất bại")

        def delete(self):
                svBUS = SinhVienBUS()
                if(svBUS.delete(self.ma)):
                        QMessageBox.information(self.centralwidget,"Thông báo","Xóa thành công")
                        self.loadDataQTable()
                        self.clear()
                else:
                        QMessageBox.information(self.centralwidget,"Thông báo","Xóa thất bại")
        def find(self):
                sv = SinhVienBUS()
                key =  self.cmbOptionFindSV.currentData() 
                value = self.txtFindSV.text()
                #print(key)
                list = sv.find(key, value)
                tablerow=0
                self.tbwSV.setRowCount(list.__len__())
                #print(list)
                if list is not None:
                        for row in list:
                                self.tbwSV.setItem(
                                tablerow, 0, QtWidgets.QTableWidgetItem(row[0]))
                                self.tbwSV.setItem(
                                tablerow, 1, QtWidgets.QTableWidgetItem(row[1]))
                                self.tbwSV.setItem(
                                tablerow, 2, QtWidgets.QTableWidgetItem(row[2]))
                                self.tbwSV.setItem(
                                tablerow, 3, QtWidgets.QTableWidgetItem(row[3]))
                                self.tbwSV.setItem(
                                tablerow, 4, QtWidgets.QTableWidgetItem(row[4]))
                                self.tbwSV.setItem(
                                tablerow, 5, QtWidgets.QTableWidgetItem(str(row[5])))
                                self.tbwSV.setItem(
                                tablerow, 6, QtWidgets.QTableWidgetItem(row[6]))
                                self.tbwSV.setItem(
                                tablerow, 7, QtWidgets.QTableWidgetItem("0"+str(row[7])))
                                self.tbwSV.setItem(
                                tablerow, 8, QtWidgets.QTableWidgetItem(str(row[8])))
                                tablerow += 1

        # Quản lý lớp

        def loadDataQTableLop(self):

                lop = LopBUS()
                list = lop.get()
                tablerow = 0
                self.tbwLop.setRowCount(list.__len__())
                if list is not None:
                        for row in list:
                                self.tbwLop.setItem(
                                tablerow, 0, QtWidgets.QTableWidgetItem(row[0]))
                                self.tbwLop.setItem(
                                tablerow, 1, QtWidgets.QTableWidgetItem(row[1]))
                                tablerow += 1


        def getDataRowLop(self):
                cr = self.tbwLop.currentRow()
                self.maL = self.tbwLop.item(cr, 0).text()
                self.txtLop2.setText(self.tbwLop.item(cr, 1).text())


        def clearLop(self):
                self.txtLop2.clear()
                
        def validateLop(self, l: Lop):        
                if l._tenlop == '':
                        QMessageBox.information(self.centralwidget,"Thông báo","Vui lòng nhập đầy đủ thông tin")
                        return False
                if LopBUS.checkTenLopTonTai(self, tenlop=l._tenlop) == False:
                        QMessageBox.information(self.centralwidget,"Thông báo","Tên lớp đã tồn tại")
                        return False
                return True

        def addLop(self):
                lopBUS = LopBUS()
                malop = lopBUS.generateID()
                tenlop = self.txtLop2.text()
                
                lop = Lop(malop, tenlop)
                if self.validateLop(lop):                
                        if(lopBUS.add(lop)):
                                QMessageBox.information(self.centralwidget,"Thông báo","Thêm thành công")
                                self.loadDataQTableLop()
                                self.clear()
                        else:
                                QMessageBox.information(self.centralwidget,"Thông báo","Thêm thất bại")

        def updateLop(self):
                lopBUS = LopBUS()
                malop = self.maL
                tenlop = self.txtLop2.text()
                lop = Lop(malop, tenlop)
                if self.validateLop(lop):   
                        if(lopBUS.update(lop)):
                                QMessageBox.information(self.centralwidget,"Thông báo","Cập nhật thành công")
                                self.loadDataQTableLop()
                        else:
                                QMessageBox.information(self.centralwidget,"Thông báo","Cập nhật thất bại")

        def deleteLop(self):
                lopBUS = LopBUS()
                if(lopBUS.delete(self.maL)):
                        QMessageBox.information(self.centralwidget,"Thông báo","Xóa thành công")
                        self.loadDataQTableLop()
                        self.clear()
                else:
                        QMessageBox.information(self.centralwidget,"Thông báo","Xóa thất bại")
        def findLop(self):
                if hasattr(self, 'txtFindLop'):
                        lop = LopBUS()
                        key =  self.cmbOptionFindLop.currentData()
                        value = self.txtFindLop.text()
                        list = lop.find(key, value)
                        tablerow=0
                        self.tbwLop.setRowCount(list.__len__())
                        if list is not None:
                                for row in list:
                                        self.tbwLop.setItem(
                                        tablerow, 0, QtWidgets.QTableWidgetItem(row[0]))
                                        self.tbwLop.setItem(
                                        tablerow, 1, QtWidgets.QTableWidgetItem(row[1]))
                                        tablerow += 1
        def show_camera(self):
                # Tạo một đối tượng MainWindow để hiển thị video từ camera
                # self.camera = face_dataset(id=self.ma)
                # self.camera.show()

                self.MainWindow = QtWidgets.QMainWindow()
                self.camera = CameraLayAnh(id=self.ma)
                self.camera.setupUi(self.MainWindow)
                self.MainWindow.show()


        def show_image(self):
                self.MainWindow = QtWidgets.QMainWindow()
                self.ui = ViewImage(id=self.ma)
                self.ui.setupUi(self.MainWindow)
                self.MainWindow.show()

        
        def trainImage(self):
                train = face_training()
                train.train()
        
        def clock_number(self):
                time = datetime.now()
                format_time = time.strftime("%H:%M:%S")
                self.label_2.setText(format_time)

                format_date = time.strftime("%d/%m/%Y")
                self.label_4.setText(format_date)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UI_QuanLySinhVien()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())