# Form implementation generated from reading ui file 'ui/QuanLyDiemDanh.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox
import os
import sys
import time
import pandas as pd
import win32com.client as win32
import openpyxl
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.dirname(SCRIPT_DIR))
from BUS.DiemDanhBUS import DiemDanhBUS
from DAL.DiemDanh import DiemDanh

class UI_QuanLyDiemDanh(object):
        ma = ""
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(800, 590)
                self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.frmChangeBuoiHoc = QtWidgets.QFrame(parent=self.centralwidget)
                self.frmChangeBuoiHoc.setGeometry(QtCore.QRect(19, 99, 231, 471))
                self.frmChangeBuoiHoc.setStyleSheet("#frmChangeBuoiHoc\n"
"{\n"
"    border-width: 2;\n"
"    border-radius: 5;\n"
"     border-style: solid;\n"
"      border-color: #457fca;\n"
"}")
                self.frmChangeBuoiHoc.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
                self.frmChangeBuoiHoc.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
                self.frmChangeBuoiHoc.setObjectName("frmChangeBuoiHoc")
                self.label_5 = QtWidgets.QLabel(parent=self.frmChangeBuoiHoc)
                self.label_5.setGeometry(QtCore.QRect(10, 6, 211, 31))
                font = QtGui.QFont()
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.label_5.setFont(font)
                self.label_5.setStyleSheet("#label_5\n"
"{\n"
"    font-weight:bold;\n"
"}")
                self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                self.label_5.setObjectName("label_5")
                self.label_11 = QtWidgets.QLabel(parent=self.frmChangeBuoiHoc)
                self.label_11.setGeometry(QtCore.QRect(19, 170, 74, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_11.setFont(font)
                self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_11.setObjectName("label_11")
                self.timeGioVao = QtWidgets.QTimeEdit(parent=self.frmChangeBuoiHoc)
                self.timeGioVao.setGeometry(QtCore.QRect(97, 170, 121, 22))
                self.timeGioVao.setObjectName("timeGioVao")
                self.timeGioVao.setDisplayFormat("HH:mm:ss")
                self.label_12 = QtWidgets.QLabel(parent=self.frmChangeBuoiHoc)
                self.label_12.setGeometry(QtCore.QRect(19, 210, 74, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_12.setFont(font)
                self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_12.setObjectName("label_12")
                self.timeGioRa = QtWidgets.QTimeEdit(parent=self.frmChangeBuoiHoc)
                self.timeGioRa.setGeometry(QtCore.QRect(97, 210, 121, 22))
                self.timeGioRa.setObjectName("timeGioRa")
                self.timeGioRa.setDisplayFormat("HH:mm:ss")
                self.label_13 = QtWidgets.QLabel(parent=self.frmChangeBuoiHoc)
                self.label_13.setGeometry(QtCore.QRect(19, 250, 74, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_13.setFont(font)
                self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_13.setObjectName("label_13")
                self.dateNgay = QtWidgets.QDateEdit(parent=self.frmChangeBuoiHoc)
                self.dateNgay.setGeometry(QtCore.QRect(97, 250, 121, 22))
                self.dateNgay.setObjectName("dateNgay")
                self.dateNgay.setDisplayFormat("yyyy-MM-dd")
                self.dateNgay.setDate(QtCore.QDate.currentDate())
                self.label_14 = QtWidgets.QLabel(parent=self.frmChangeBuoiHoc)
                self.label_14.setGeometry(QtCore.QRect(19, 130, 74, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_14.setFont(font)
                self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_14.setObjectName("label_14")
                self.cmbLop = QtWidgets.QComboBox(parent=self.frmChangeBuoiHoc)
                self.cmbLop.setGeometry(QtCore.QRect(97, 130, 121, 22))
                self.cmbLop.setObjectName("cmbLop")
                self.cmbLop.setEditable(False)
                self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.frmChangeBuoiHoc)
                self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 370, 211, 41))
                self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
                self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
                self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout.setSpacing(10)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.btnCapNhat = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
                self.btnCapNhat.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnCapNhat.setStyleSheet("#btnCapNhat{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"color:white;\n"
"font-weight:bold;\n"
"border-radius:3px;\n"
"padding: 5px;\n"
"}\n"
"#btnCapNhat:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"}")
                self.btnCapNhat.setObjectName("btnCapNhat")
                self.btnCapNhat.clicked.connect(self.update)
                self.horizontalLayout.addWidget(self.btnCapNhat)
                self.btnXoa = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
                self.btnXoa.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnXoa.setStyleSheet("#btnXoa{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"color:white;\n"
"font-weight:bold;\n"
"border-radius:3px;\n"
"padding: 5px;\n"
"}\n"
"#btnXoa:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"}")
                self.btnXoa.setObjectName("btnXoa")
                self.btnXoa.clicked.connect(self.delete)
                self.horizontalLayout.addWidget(self.btnXoa)
                self.btnLamMoi = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
                self.btnLamMoi.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnLamMoi.setStyleSheet("#btnLamMoi{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"color:white;\n"
"font-weight:bold;\n"
"border-radius:3px;\n"
"padding: 5px;\n"
"}\n"
"#btnLamMoi:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"}")
                self.btnLamMoi.setObjectName("btnLamMoi")
                self.btnLamMoi.clicked.connect(self.clear)
                self.horizontalLayout.addWidget(self.btnLamMoi)
                self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.frmChangeBuoiHoc)
                self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 420, 211, 41))
                self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
                self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_2.setSpacing(10)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.btnImport = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
                self.btnImport.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnImport.setStyleSheet("#btnImport{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"color:white;\n"
"font-weight:bold;\n"
"border-radius:3px;\n"
"padding: 5px;\n"
"}\n"
"#btnImport:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"}")
                self.btnImport.setObjectName("btnImport")
                self.btnImport.clicked.connect(self.importExcel)
                self.horizontalLayout_2.addWidget(self.btnImport)
                self.btnExport = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
                self.btnExport.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnExport.setStyleSheet("#btnExport{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"color:white;\n"
"font-weight:bold;\n"
"border-radius:3px;\n"
"padding: 5px;\n"
"}\n"
"#btnExport:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"}")
                self.btnExport.setObjectName("btnExport")
                self.btnExport.clicked.connect(self.exportExcel)
                self.horizontalLayout_2.addWidget(self.btnExport)
                self.btnXemAnh = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
                self.btnXemAnh.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnXemAnh.setStyleSheet("#btnXemAnh{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"color:white;\n"
"font-weight:bold;\n"
"border-radius:3px;\n"
"padding: 5px;\n"
"}\n"
"#btnXemAnh:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"}")
                self.btnXemAnh.setObjectName("btnXemAnh")
                self.horizontalLayout_2.addWidget(self.btnXemAnh)
                self.txtIDSV = QtWidgets.QLineEdit(parent=self.frmChangeBuoiHoc)
                self.txtIDSV.setGeometry(QtCore.QRect(97, 50, 121, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.txtIDSV.setFont(font)
                self.txtIDSV.setObjectName("txtIDSV")
                self.txtIDSV.setReadOnly(True)
                self.txtIDSV.setStyleSheet("QLineEdit { background: #F2F2F2};") ##
                self.label_15 = QtWidgets.QLabel(parent=self.frmChangeBuoiHoc)
                self.label_15.setGeometry(QtCore.QRect(19, 50, 74, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_15.setFont(font)
                self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_15.setObjectName("label_15")
                self.txtHoTen = QtWidgets.QLineEdit(parent=self.frmChangeBuoiHoc)
                self.txtHoTen.setGeometry(QtCore.QRect(97, 90, 121, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.txtHoTen.setFont(font)
                self.txtHoTen.setObjectName("txtHoTen")
                self.txtHoTen.setReadOnly(True)
                self.txtHoTen.setStyleSheet("QLineEdit { background: #F2F2F2};")
                self.label_16 = QtWidgets.QLabel(parent=self.frmChangeBuoiHoc)
                self.label_16.setGeometry(QtCore.QRect(19, 90, 74, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_16.setFont(font)
                self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_16.setObjectName("label_16")
                self.cmbIDBuoiHoc = QtWidgets.QComboBox(parent=self.frmChangeBuoiHoc)
                self.cmbIDBuoiHoc.setGeometry(QtCore.QRect(97, 290, 121, 22))
                self.cmbIDBuoiHoc.setObjectName("cmbIDBuoiHoc")
                self.label_19 = QtWidgets.QLabel(parent=self.frmChangeBuoiHoc)
                self.label_19.setGeometry(QtCore.QRect(19, 290, 74, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_19.setFont(font)
                self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_19.setObjectName("label_19")
                self.label_20 = QtWidgets.QLabel(parent=self.frmChangeBuoiHoc)
                self.label_20.setGeometry(QtCore.QRect(19, 330, 74, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_20.setFont(font)
                self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_20.setObjectName("label_20")
                self.txtDiemDanh = QtWidgets.QLineEdit(parent=self.frmChangeBuoiHoc)
                self.txtDiemDanh.setGeometry(QtCore.QRect(97, 330, 121, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.txtDiemDanh.setFont(font)
                self.txtDiemDanh.setObjectName("txtDiemDanh")
                self.frmInfoBuoiHoc = QtWidgets.QFrame(parent=self.centralwidget)
                self.frmInfoBuoiHoc.setGeometry(QtCore.QRect(270, 100, 511, 471))
                self.frmInfoBuoiHoc.setStyleSheet("#frmInfoBuoiHoc\n"
"{\n"
"    border-width: 2;\n"
"    border-radius: 5;\n"
"     border-style: solid;\n"
"      border-color: #457fca;\n"
"}")
                self.frmInfoBuoiHoc.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
                self.frmInfoBuoiHoc.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
                self.frmInfoBuoiHoc.setObjectName("frmInfoBuoiHoc")
                self.frame_3 = QtWidgets.QFrame(parent=self.frmInfoBuoiHoc)
                self.frame_3.setGeometry(QtCore.QRect(20, 10, 471, 71))
                self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.Box)
                self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
                self.frame_3.setObjectName("frame_3")
                self.label_17 = QtWidgets.QLabel(parent=self.frame_3)
                self.label_17.setGeometry(QtCore.QRect(10, 10, 131, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_17.setFont(font)
                self.label_17.setObjectName("label_17")
                self.label_18 = QtWidgets.QLabel(parent=self.frame_3)
                self.label_18.setGeometry(QtCore.QRect(10, 36, 101, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_18.setFont(font)
                self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
                self.label_18.setObjectName("label_18")
                self.cmbOptionFind = QtWidgets.QComboBox(parent=self.frame_3)
                self.cmbOptionFind.setGeometry(QtCore.QRect(110, 36, 101, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.cmbOptionFind.setFont(font)
                self.cmbOptionFind.setObjectName("cmbOptionFind")
                self.cmbOptionFind.addItem("ID điểm danh", "madiemdanh")
                self.cmbOptionFind.addItem("Mã sinh viên", "masinhvien")
                self.cmbOptionFind.addItem("Họ tên", "hoten")
                self.cmbOptionFind.addItem("Lớp học", "tenlop")
                self.cmbOptionFind.addItem("Giờ vào", "giovao")
                self.cmbOptionFind.addItem("Giờ ra", "giora")
                self.cmbOptionFind.addItem("Ngày", "ngay")
                self.cmbOptionFind.addItem("ID buổi học", "mabuoihoc")
                self.cmbOptionFind.addItem("Điểm danh", "trangthai")
                self.cmbOptionFind.currentIndexChanged.connect(self.find)
                self.txtFind = QtWidgets.QLineEdit(parent=self.frame_3)
                self.txtFind.setGeometry(QtCore.QRect(220, 36, 231, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.txtFind.setFont(font)
                self.txtFind.setText("")
                self.txtFind.setObjectName("txtFind")
                self.txtFind.textChanged.connect(self.find)
                self.tbwDiemDanh = QtWidgets.QTableWidget(parent=self.frmInfoBuoiHoc)
                self.tbwDiemDanh.setGeometry(QtCore.QRect(20, 90, 471, 361))
                self.tbwDiemDanh.setObjectName("tbwDiemDanh")
                self.tbwDiemDanh.setColumnCount(9)
                self.tbwDiemDanh.setRowCount(0)
                item = QtWidgets.QTableWidgetItem()
                self.tbwDiemDanh.setHorizontalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwDiemDanh.setHorizontalHeaderItem(1, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwDiemDanh.setHorizontalHeaderItem(2, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwDiemDanh.setHorizontalHeaderItem(3, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwDiemDanh.setHorizontalHeaderItem(4, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwDiemDanh.setHorizontalHeaderItem(5, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwDiemDanh.setHorizontalHeaderItem(6, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwDiemDanh.setHorizontalHeaderItem(7, item)
                item = QtWidgets.QTableWidgetItem()
                self.tbwDiemDanh.setHorizontalHeaderItem(8, item)
                self.tbwDiemDanh.setEditTriggers(QtWidgets.QTableWidget.EditTrigger.NoEditTriggers)
                self.tbwDiemDanh.itemClicked.connect(self.getDataRow)
                self.frmHeader = QtWidgets.QFrame(parent=self.centralwidget)
                self.frmHeader.setGeometry(QtCore.QRect(0, 30, 851, 51))
                self.frmHeader.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
                self.frmHeader.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
                self.frmHeader.setObjectName("frmHeader")
                self.label_3 = QtWidgets.QLabel(parent=self.frmHeader)
                self.label_3.setGeometry(QtCore.QRect(0, 0, 801, 51))
                font = QtGui.QFont()
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.label_3.setFont(font)
                self.label_3.setStyleSheet("#label_3\n"
"{\n"
"    font-weight:bold;\n"
"}")
                self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                self.label_3.setObjectName("label_3")
                self.btnBack = QtWidgets.QPushButton(parent=self.frmHeader)
                self.btnBack.setGeometry(QtCore.QRect(730, 12, 61, 23))
                self.btnBack.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnBack.setObjectName("btnBack")
                self.label_2 = QtWidgets.QLabel(parent=self.frmHeader)
                self.label_2.setGeometry(QtCore.QRect(50, 10, 91, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setStyleStrategy(QtGui.QFont.StyleStrategy.NoAntialias)
                self.label_2.setFont(font)
                self.label_2.setAcceptDrops(False)
                self.label_2.setToolTip("")
                self.label_2.setAutoFillBackground(False)
                self.label_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
                self.label_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
                self.label_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
                self.label_2.setScaledContents(False)
                self.label_2.setWordWrap(False)
                self.label_2.setIndent(-1)
                self.label_2.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
                self.label_2.setObjectName("label_2")
                self.label_4 = QtWidgets.QLabel(parent=self.frmHeader)
                self.label_4.setGeometry(QtCore.QRect(50, 30, 91, 16))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label_4.setFont(font)
                self.label_4.setObjectName("label_4")
                self.btnDark = QtWidgets.QPushButton(parent=self.frmHeader)
                self.btnDark.setGeometry(QtCore.QRect(680, 8, 31, 31))
                self.btnDark.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnDark.setText("")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("ui\\../image/moon_symbol_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.btnDark.setIcon(icon)
                self.btnDark.setIconSize(QtCore.QSize(20, 20))
                self.btnDark.setObjectName("btnDark")
                self.btnTime = QtWidgets.QPushButton(parent=self.frmHeader)
                self.btnTime.setGeometry(QtCore.QRect(10, 10, 31, 31))
                self.btnTime.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnTime.setStyleSheet("#btnTime\n"
"{\n"
"background-color: transparent;\n"
"}")
                self.btnTime.setText("")
                icon1 = QtGui.QIcon()
                icon1.addPixmap(QtGui.QPixmap("ui\\../image/time_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.btnTime.setIcon(icon1)
                self.btnTime.setIconSize(QtCore.QSize(20, 20))
                self.btnTime.setObjectName("btnTime")
                self.label_3.raise_()
                self.btnBack.raise_()
                self.label_4.raise_()
                self.label_2.raise_()
                self.btnDark.raise_()
                self.btnTime.raise_()
                self.frame = QtWidgets.QFrame(parent=self.centralwidget)
                self.frame.setGeometry(QtCore.QRect(0, 0, 801, 31))
                self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
                self.frame.setObjectName("frame")
                self.btnClose = QtWidgets.QPushButton(parent=self.frame)
                self.btnClose.setGeometry(QtCore.QRect(777, 4, 24, 24))
                self.btnClose.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnClose.setText("")
                icon2 = QtGui.QIcon()
                icon2.addPixmap(QtGui.QPixmap("ui\\../image/close_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.btnClose.setIcon(icon2)
                self.btnClose.setIconSize(QtCore.QSize(20, 20))
                self.btnClose.setObjectName("btnClose")
                self.btnMinimize = QtWidgets.QPushButton(parent=self.frame)
                self.btnMinimize.setGeometry(QtCore.QRect(752, 4, 24, 24))
                self.btnMinimize.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.btnMinimize.setText("")
                icon3 = QtGui.QIcon()
                icon3.addPixmap(QtGui.QPixmap("ui\\../image/subtract_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.btnMinimize.setIcon(icon3)
                self.btnMinimize.setIconSize(QtCore.QSize(20, 20))
                self.btnMinimize.setObjectName("btnMinimize")
                self.label_21 = QtWidgets.QLabel(parent=self.frame)
                self.label_21.setGeometry(QtCore.QRect(10, 2, 201, 26))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setStyleStrategy(QtGui.QFont.StyleStrategy.NoAntialias)
                self.label_21.setFont(font)
                self.label_21.setAcceptDrops(False)
                self.label_21.setToolTip("")
                self.label_21.setAutoFillBackground(False)
                self.label_21.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
                self.label_21.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
                self.label_21.setTextFormat(QtCore.Qt.TextFormat.AutoText)
                self.label_21.setScaledContents(False)
                self.label_21.setWordWrap(False)
                self.label_21.setIndent(-1)
                self.label_21.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
                self.label_21.setObjectName("label_21")
                MainWindow.setCentralWidget(self.centralwidget)

                self.loadDataQTable()
                self.loadDataCmbLop()
                self.loadDataCmbIdBH()
                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label_5.setText(_translate("MainWindow", "Cập nhật điểm danh"))
                self.label_11.setText(_translate("MainWindow", "Giờ vào"))
                self.label_12.setText(_translate("MainWindow", "Giờ ra"))
                self.label_13.setText(_translate("MainWindow", "Ngày"))
                self.label_14.setText(_translate("MainWindow", "Lớp học"))
                self.btnCapNhat.setText(_translate("MainWindow", "Cập nhật"))
                self.btnXoa.setText(_translate("MainWindow", "Xóa"))
                self.btnLamMoi.setText(_translate("MainWindow", "Làm mới"))
                self.btnImport.setText(_translate("MainWindow", "Import"))
                self.btnExport.setText(_translate("MainWindow", "Export"))
                self.btnXemAnh.setText(_translate("MainWindow", "Xem ảnh"))
                self.label_15.setText(_translate("MainWindow", "Mã SV"))
                self.label_16.setText(_translate("MainWindow", "Họ tên"))
                self.label_19.setText(_translate("MainWindow", "ID buổi học"))
                self.label_20.setText(_translate("MainWindow", "Điểm danh"))
                self.label_17.setText(_translate("MainWindow", "Hệ thống tìm kiếm:"))
                self.label_18.setText(_translate("MainWindow", "Tìm kiếm theo:"))
                self.cmbOptionFind.setItemText(0, _translate("MainWindow", "ID điểm danh"))
                item = self.tbwDiemDanh.horizontalHeaderItem(0)
                item.setText(_translate("MainWindow", "ID điểm danh"))
                item = self.tbwDiemDanh.horizontalHeaderItem(1)
                item.setText(_translate("MainWindow", "Mã SV"))
                item = self.tbwDiemDanh.horizontalHeaderItem(2)
                item.setText(_translate("MainWindow", "Họ tên"))
                item = self.tbwDiemDanh.horizontalHeaderItem(3)
                item.setText(_translate("MainWindow", "Lớp học"))
                item = self.tbwDiemDanh.horizontalHeaderItem(4)
                item.setText(_translate("MainWindow", "Giờ vào"))
                item = self.tbwDiemDanh.horizontalHeaderItem(5)
                item.setText(_translate("MainWindow", "Giờ ra"))
                item = self.tbwDiemDanh.horizontalHeaderItem(6)
                item.setText(_translate("MainWindow", "Ngày"))
                item = self.tbwDiemDanh.horizontalHeaderItem(7)
                item.setText(_translate("MainWindow", "ID buổi học"))
                item = self.tbwDiemDanh.horizontalHeaderItem(8)
                item.setText(_translate("MainWindow", "Điểm danh"))
                self.label_3.setText(_translate("MainWindow", "Quản lý thông tin điểm danh"))
                self.btnBack.setText(_translate("MainWindow", "Trở về"))
                self.label_21.setText(_translate("MainWindow", "Phần mềm điểm danh sinh viên"))

        def loadDataQTable(self):

                dd = DiemDanhBUS()
                list = dd.get()
                tablerow=0
                self.tbwDiemDanh.setRowCount(list.__len__())
             
                if list is not None:
                        for row in list:
                                self.tbwDiemDanh.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(str(row[0])))
                                self.tbwDiemDanh.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(str(row[1])))
                                self.tbwDiemDanh.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(str(row[2])))
                                self.tbwDiemDanh.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(str(row[3])))
                                self.tbwDiemDanh.setItem(tablerow, 4, QtWidgets.QTableWidgetItem(str(row[4])))
                                self.tbwDiemDanh.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(str(row[5])))
                                self.tbwDiemDanh.setItem(tablerow, 6, QtWidgets.QTableWidgetItem(str(row[6])))
                                self.tbwDiemDanh.setItem(tablerow, 7, QtWidgets.QTableWidgetItem(str(row[7])))
                                self.tbwDiemDanh.setItem(tablerow, 8, QtWidgets.QTableWidgetItem(str(row[8])))
                                
                                tablerow+=1

        def loadDataCmbLop(self):

                dd = DiemDanhBUS()
                list = dd.getCmbLop()
                self.cmbLop.addItem("Chọn Lớp Học")
                if list is not None:
                        for row in list:
                                self.cmbLop.addItem(row[0])
        
        def loadDataCmbIdBH(self):

                dd = DiemDanhBUS()
                list = dd.getCmbIdBH()
                self.cmbIDBuoiHoc.addItem("Chọn ID buổi học")
                if list is not None:
                        for row in list:
                                self.cmbIDBuoiHoc.addItem(row[0])

        def getDataRow(self):

                cr = self.tbwDiemDanh.currentRow() 

                time_str_Vao = self.tbwDiemDanh.item(cr,4).text()
                time_str_Ra = self.tbwDiemDanh.item(cr,5).text()
                date_str = self.tbwDiemDanh.item(cr,6).text()
                time_format =  "%H:%M:%S"
                date_format = "%Y-%m-%d"
                
                timeVao = datetime.datetime.strptime(time_str_Vao,time_format).time()
                timeRa = datetime.datetime.strptime(time_str_Ra,time_format).time()
                date = datetime.datetime.strptime(date_str,date_format).date()

                self.ma = self.tbwDiemDanh.item(cr,0).text()
                self.txtIDSV.setText(self.tbwDiemDanh.item(cr,1).text())
                self.txtHoTen.setText(self.tbwDiemDanh.item(cr,2).text())
                
                self.cmbLop.setCurrentText(self.tbwDiemDanh.item(cr,3).text())
                self.timeGioVao.setTime(timeVao)
                self.timeGioRa.setTime(timeRa)
                self.dateNgay.setDate(date)
                self.cmbIDBuoiHoc.setCurrentText(self.tbwDiemDanh.item(cr,7).text())
                self.txtDiemDanh.setText(self.tbwDiemDanh.item(cr,8).text())

        def clear(self):

                self.txtIDSV.clear()
                self.txtHoTen.clear()
                self.timeGioVao.setTime(QtCore.QTime(7, 00, 00))
                self.timeGioRa.setTime(QtCore.QTime(17, 30, 00))
                self.dateNgay.setDate(QtCore.QDate.currentDate())
                self.cmbLop.clear()
                self.loadDataCmbLop()
                self.cmbIDBuoiHoc.clear()
                self.loadDataCmbIdBH()
                self.txtDiemDanh.clear()
        
        def update(self):

                ddBUS = DiemDanhBUS()
                madiemdanh = self.ma
                masinhvien = self.txtIDSV.text()
                giovao = self.timeGioVao.text()
                giora = self.timeGioRa.text()
                ngay = self.dateNgay.text()
                mabuoihoc = self.cmbIDBuoiHoc.currentText()
                trangthai = self.txtDiemDanh.text()
                
                dd = DiemDanh(madiemdanh, masinhvien, giovao, giora, ngay, mabuoihoc, trangthai)
                
                if(ddBUS.update(dd)):
                        QMessageBox.information(self.centralwidget,"Thông báo","Cập nhật thành công")
                        self.loadDataQTable()
                else:
                        QMessageBox.information(self.centralwidget,"Thông báo","Cập nhật thất bại")

        def delete(self):

                ddBUS = DiemDanhBUS()
                if(ddBUS.delete(self.ma)):
                        QMessageBox.information(self.centralwidget,"Thông báo","Xóa thành công")
                        self.loadDataQTable()
                        self.clear()
                else:
                        QMessageBox.information(self.centralwidget,"Thông báo","Xóa thất bại")

        def find(self):

                dd = DiemDanhBUS()
                key =  self.cmbOptionFind.currentData()
                value = self.txtFind.text()
                list = dd.find(key, value)
                tablerow=0
                self.tbwDiemDanh.setRowCount(list.__len__())
             
                if list is not None:
                        for row in list:
                                self.tbwDiemDanh.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(str(row[0])))
                                self.tbwDiemDanh.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(str(row[1])))
                                self.tbwDiemDanh.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(str(row[2])))
                                self.tbwDiemDanh.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(str(row[3])))
                                self.tbwDiemDanh.setItem(tablerow, 4, QtWidgets.QTableWidgetItem(str(row[4])))
                                self.tbwDiemDanh.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(str(row[5])))
                                self.tbwDiemDanh.setItem(tablerow, 6, QtWidgets.QTableWidgetItem(str(row[6])))
                                self.tbwDiemDanh.setItem(tablerow, 7, QtWidgets.QTableWidgetItem(str(row[7])))
                                self.tbwDiemDanh.setItem(tablerow, 8, QtWidgets.QTableWidgetItem(str(row[8])))
                                
                                tablerow+=1

        def importExcel(self):

                dir_path = r"FileExcel\DiemDanh.xlsx"
                ddBUS = DiemDanhBUS()
                wb = openpyxl.load_workbook(dir_path)
                sheet = wb.active
                # # # Tạo vòng lặp For để lặp qua từng hàng trong tệp xlsx, 
                # # # bắt đầu từ hàng 2 bỏ qua các tiêu đề
                for r in range(1, sheet.max_row+1):
                        madiemdanh = sheet.cell(r,1).value
                        masinhvien = sheet.cell(r,2).value
                        giovao = sheet.cell(r,5).value
                        giora = sheet.cell(r,6).value
                        ngay = sheet.cell(r,7).value
                        mabuoihoc = sheet.cell(r,8).value
                        trangthai = sheet.cell(r,9).value
                        # print(madiemdanh,masinhvien,giovao,giora,ngay,mabuoihoc,trangthai)

                        dd = DiemDanh(madiemdanh, masinhvien, giovao, giora, ngay, mabuoihoc, trangthai)
                        # print(madiemdanh,masinhvien,giovao,giora,ngay,mabuoihoc,trangthai)

                        if(ddBUS.add(dd)):
                                QMessageBox.information(self.centralwidget,"Thông báo","Import thành công")
                                self.loadDataQTable()
                                print(madiemdanh,masinhvien,giovao,giora,ngay,mabuoihoc,trangthai)
                        else:
                                QMessageBox.information(self.centralwidget,"Thông báo","Import thất bại")

        def exportExcel(self):

                columnHeaders = []

                # Tạo danh sách tiêu đề cột
                for j in range(self.tbwDiemDanh.model().columnCount()):
                        columnHeaders.append(self.tbwDiemDanh.horizontalHeaderItem(j).text())

                df = pd.DataFrame(columns=columnHeaders)

                # Tạo bộ bản ghi đối tượng khung dữ liệu
                for row in range(self.tbwDiemDanh.rowCount()):
                        for col in range(self.tbwDiemDanh.columnCount()):
                                df.at[row, columnHeaders[col]] = self.tbwDiemDanh.item(row, col).text()

                t = time.localtime()
                current_time = time.strftime("%H%M%S", t)       
                tenfile =  "FileExcel\DiemDanh\DiemDanh{}.xlsx".format(current_time)
                df.to_excel(tenfile, index=False)

                if(columnHeaders != ""):
                        QMessageBox.information(self.centralwidget,"Thông báo","Export thành công")
                        
                        # Gọi đường dẫn
                        dir_path = os.getcwd()
                        ## Kiểm tra có phải excel ko, khởi động excel
                        excel = win32.gencache.EnsureDispatch('Excel.Application')
                        excel.Workbooks.Open(os.path.join(dir_path,tenfile))
                        excel.Visible = True
                        print('Excel file exported')
                else:
                        QMessageBox.information(self.centralwidget,"Thông báo","Export thất bại")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UI_QuanLyDiemDanh()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
