# Form implementation generated from reading ui file 'ui/QuanLyBuoiHoc.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox
import os
import sys
import datetime
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.dirname(SCRIPT_DIR))
from BUS.BuoiHocBUS import BuoiHocBUS
from DAL.BuoiHoc import BuoiHoc


class UI_QuanLyBuoiHoc(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 590)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frmHeader = QtWidgets.QFrame(parent=self.centralwidget)
        self.frmHeader.setGeometry(QtCore.QRect(1, 31, 851, 51))
        self.frmHeader.setAccessibleName("")
        self.frmHeader.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frmHeader.setStyleSheet("#frmHeader{background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255))}\n"
"")
        self.frmHeader.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frmHeader.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frmHeader.setLineWidth(1)
        self.frmHeader.setObjectName("frmHeader")
        self.label_3 = QtWidgets.QLabel(parent=self.frmHeader)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 801, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("#label_3\n"
"{\n"
"    font-weight:bold;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btnBack = QtWidgets.QPushButton(parent=self.frmHeader)
        self.btnBack.setGeometry(QtCore.QRect(730, 12, 61, 23))
        self.btnBack.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnBack.setObjectName("btnBack")
        self.label_2 = QtWidgets.QLabel(parent=self.frmHeader)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.NoAntialias)
        self.label_2.setFont(font)
        self.label_2.setAcceptDrops(False)
        self.label_2.setToolTip("")
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setIndent(-1)
        self.label_2.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.frmHeader)
        self.label_4.setGeometry(QtCore.QRect(50, 30, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnDark = QtWidgets.QPushButton(parent=self.frmHeader)
        self.btnDark.setGeometry(QtCore.QRect(680, 8, 31, 31))
        self.btnDark.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnDark.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../image/moon_symbol_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnDark.setIcon(icon)
        self.btnDark.setIconSize(QtCore.QSize(20, 20))
        self.btnDark.setObjectName("btnDark")
        self.btnTime = QtWidgets.QPushButton(parent=self.frmHeader)
        self.btnTime.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.btnTime.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnTime.setStyleSheet("#btnTime\n"
"{\n"
"background-color: transparent;\n"
"}")
        self.btnTime.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\../image/time_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnTime.setIcon(icon1)
        self.btnTime.setIconSize(QtCore.QSize(20, 20))
        self.btnTime.setObjectName("btnTime")
        self.label_3.raise_()
        self.btnBack.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.btnDark.raise_()
        self.btnTime.raise_()
        self.frmChangeBuoiHoc = QtWidgets.QFrame(parent=self.centralwidget)
        self.frmChangeBuoiHoc.setGeometry(QtCore.QRect(20, 100, 231, 471))
        self.frmChangeBuoiHoc.setStyleSheet("#frmChangeBuoiHoc\n"
"{\n"
"    border-width: 2;\n"
"    border-radius: 5;\n"
"     border-style: solid;\n"
"      border-color: #457fca;\n"
"}")
        self.frmChangeBuoiHoc.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frmChangeBuoiHoc.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frmChangeBuoiHoc.setObjectName("frmChangeBuoiHoc")
        self.label_5 = QtWidgets.QLabel(parent=self.frmChangeBuoiHoc)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("#label_5\n"
"{\n"
"    font-weight:bold;\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(parent=self.frmChangeBuoiHoc)
        self.label_11.setGeometry(QtCore.QRect(20, 70, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_11.setObjectName("label_11")
        self.timeGioBD = QtWidgets.QTimeEdit(parent=self.frmChangeBuoiHoc)
        self.timeGioBD.setGeometry(QtCore.QRect(90, 70, 121, 22))
        self.timeGioBD.setDisplayFormat("HH:mm:ss")
        self.timeGioBD.setObjectName("timeGioBD")
        self.timeGioBD.setTime(QtCore.QTime(7, 00, 00))
        self.label_12 = QtWidgets.QLabel(parent=self.frmChangeBuoiHoc)
        self.label_12.setGeometry(QtCore.QRect(20, 120, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_12.setObjectName("label_12")
        self.timeGioKT = QtWidgets.QTimeEdit(parent=self.frmChangeBuoiHoc)
        self.timeGioKT.setGeometry(QtCore.QRect(90, 120, 121, 22))
        self.timeGioKT.setDisplayFormat("HH:mm:ss")
        self.timeGioKT.setObjectName("timeGioKT")
        self.timeGioKT.setTime(QtCore.QTime(17, 30, 00))
        self.label_13 = QtWidgets.QLabel(parent=self.frmChangeBuoiHoc)
        self.label_13.setGeometry(QtCore.QRect(20, 170, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_13.setObjectName("label_13")
        self.dateNgay = QtWidgets.QDateEdit(parent=self.frmChangeBuoiHoc)
        self.dateNgay.setGeometry(QtCore.QRect(90, 170, 121, 22))
        self.dateNgay.setDisplayFormat("yyyy-MM-dd")
        self.dateNgay.setObjectName("dateNgay")
        self.dateNgay.setDate(QtCore.QDate.currentDate())
        self.label_14 = QtWidgets.QLabel(parent=self.frmChangeBuoiHoc)
        self.label_14.setGeometry(QtCore.QRect(20, 220, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_14.setObjectName("label_14")
        self.cmbLop = QtWidgets.QComboBox(parent=self.frmChangeBuoiHoc)
        self.cmbLop.setGeometry(QtCore.QRect(90, 220, 121, 22))
        self.cmbLop.setObjectName("cmbLop")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.frmChangeBuoiHoc)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 320, 171, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnThem = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnThem.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnThem.setStyleSheet("#btnThem{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"color:white;\n"
"font-weight:bold;\n"
"border-radius:3px;\n"
"padding: 5px;\n"
"}\n"
"#btnThem:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"}")
        self.btnThem.setObjectName("btnThem")
        self.horizontalLayout.addWidget(self.btnThem)
        self.btnThem.clicked.connect(self.add)
        self.btnSua = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnSua.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSua.setStyleSheet("#btnSua{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"color:white;\n"
"font-weight:bold;\n"
"border-radius:3px;\n"
"padding: 5px;\n"
"}\n"
"#btnSua:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"}")
        self.btnSua.setObjectName("btnSua")
        self.horizontalLayout.addWidget(self.btnSua)
        self.btnSua.clicked.connect(self.update)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.frmChangeBuoiHoc)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 370, 171, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnXoa = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.btnXoa.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnXoa.setStyleSheet("#btnXoa{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"color:white;\n"
"font-weight:bold;\n"
"border-radius:3px;\n"
"padding: 5px;\n"
"}\n"
"#btnXoa:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"}")
        self.btnXoa.setObjectName("btnXoa")
        self.horizontalLayout_2.addWidget(self.btnXoa)
        self.btnXoa.clicked.connect(self.delete)
        self.btnLamMoi = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.btnLamMoi.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnLamMoi.setStyleSheet("#btnLamMoi{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"color:white;\n"
"font-weight:bold;\n"
"border-radius:3px;\n"
"padding: 5px;\n"
"}\n"
"#btnLamMoi:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"}")
        self.btnLamMoi.setObjectName("btnLamMoi")
        self.horizontalLayout_2.addWidget(self.btnLamMoi)
        self.btnLamMoi.clicked.connect(self.clear)
        self.label_26 = QtWidgets.QLabel(parent=self.frmChangeBuoiHoc)
        self.label_26.setGeometry(QtCore.QRect(20, 270, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_26.setObjectName("label_26")
        self.cmbGv = QtWidgets.QComboBox(parent=self.frmChangeBuoiHoc)
        self.cmbGv.setGeometry(QtCore.QRect(90, 270, 121, 21))
        self.cmbGv.setObjectName("magv")
        self.frmInfoBuoiHoc = QtWidgets.QFrame(parent=self.centralwidget)
        self.frmInfoBuoiHoc.setGeometry(QtCore.QRect(271, 101, 511, 471))
        self.frmInfoBuoiHoc.setStyleSheet("#frmInfoBuoiHoc\n"
"{\n"
"    border-width: 2;\n"
"    border-radius: 5;\n"
"     border-style: solid;\n"
"      border-color: #457fca;\n"
"}")
        self.frmInfoBuoiHoc.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frmInfoBuoiHoc.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frmInfoBuoiHoc.setObjectName("frmInfoBuoiHoc")
        self.frame_3 = QtWidgets.QFrame(parent=self.frmInfoBuoiHoc)
        self.frame_3.setGeometry(QtCore.QRect(20, 10, 471, 81))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.label_17 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_17.setGeometry(QtCore.QRect(10, 10, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_18.setGeometry(QtCore.QRect(10, 40, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_18.setObjectName("label_18")
        self.cmbOptionFind = QtWidgets.QComboBox(parent=self.frame_3)
        self.cmbOptionFind.setGeometry(QtCore.QRect(110, 40, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cmbOptionFind.setFont(font)
        self.cmbOptionFind.setObjectName("cmbOptionFind")
        self.cmbOptionFind.addItem("ID buổi học", "mabuoihoc")
        self.cmbOptionFind.addItem("Giờ bắt đầu", "giobatdau")
        self.cmbOptionFind.addItem("Giờ kết thúc", "gioketthuc")
        self.cmbOptionFind.addItem("Ngày", "ngay")
        self.cmbOptionFind.addItem("ID Lớp học", "malop")
        self.cmbOptionFind.addItem("ID Giảng viên", "magiangvien")
        self.cmbOptionFind.currentIndexChanged.connect(self.find)
        self.txtFind = QtWidgets.QLineEdit(parent=self.frame_3)
        self.txtFind.setGeometry(QtCore.QRect(220, 40, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtFind.setFont(font)
        self.txtFind.setText("")
        self.txtFind.setObjectName("txtFind")
        self.txtFind.textChanged.connect(self.find)
        self.tbwBuoiHoc = QtWidgets.QTableWidget(parent=self.frmInfoBuoiHoc)
        self.tbwBuoiHoc.setGeometry(QtCore.QRect(20, 100, 471, 351))
        self.tbwBuoiHoc.setObjectName("tbwBuoiHoc")
        self.tbwBuoiHoc.setColumnCount(6)
        self.tbwBuoiHoc.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbwBuoiHoc.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwBuoiHoc.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwBuoiHoc.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwBuoiHoc.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwBuoiHoc.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwBuoiHoc.setHorizontalHeaderItem(5, item)
        # self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        # self.frame.setGeometry(QtCore.QRect(0, 0, 801, 31))
        # self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        # self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tbwBuoiHoc.setEditTriggers(QtWidgets.QTableWidget.EditTrigger.NoEditTriggers)
        self.tbwBuoiHoc.itemClicked.connect(self.getDataRow)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 30, 851, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.btnClose = QtWidgets.QPushButton(parent=self.frame)
        self.btnClose.setGeometry(QtCore.QRect(777, 4, 24, 24))
        self.btnClose.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnClose.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui\\../image/close_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnClose.setIcon(icon2)
        self.btnClose.setIconSize(QtCore.QSize(20, 20))
        self.btnClose.setObjectName("btnClose")
        self.btnMinimize = QtWidgets.QPushButton(parent=self.frame)
        self.btnMinimize.setGeometry(QtCore.QRect(752, 4, 24, 24))
        self.btnMinimize.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnMinimize.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui\\../image/subtract_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnMinimize.setIcon(icon3)
        self.btnMinimize.setIconSize(QtCore.QSize(20, 20))
        self.btnMinimize.setObjectName("btnMinimize")
        self.label_15 = QtWidgets.QLabel(parent=self.frame)
        self.label_15.setGeometry(QtCore.QRect(10, 2, 201, 26))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.NoAntialias)
        self.label_15.setFont(font)
        self.label_15.setAcceptDrops(False)
        self.label_15.setToolTip("")
        self.label_15.setAutoFillBackground(False)
        self.label_15.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_15.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_15.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_15.setScaledContents(False)
        self.label_15.setWordWrap(False)
        self.label_15.setIndent(-1)
        self.label_15.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_15.setObjectName("label_15")
        MainWindow.setCentralWidget(self.centralwidget)
        self.loadDataQTable()
        self.loadDataCmbLop()
        self.loadDataCmbGv()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Quản lý buổi học"))
        self.btnBack.setText(_translate("MainWindow", "Trở về"))
        self.label_2.setText(_translate("MainWindow", "09:15:00"))
        self.label_4.setText(_translate("MainWindow", "02/02/2022"))
        self.label_5.setText(_translate("MainWindow", "THÔNG TIN BUỔI HỌC"))
        self.label_11.setText(_translate("MainWindow", "Giờ bắt đầu"))
        self.label_12.setText(_translate("MainWindow", "Giờ kết thúc"))
        self.label_13.setText(_translate("MainWindow", "Ngày"))
        self.label_14.setText(_translate("MainWindow", "Lớp học"))
        self.btnThem.setText(_translate("MainWindow", "Thêm"))
        self.btnSua.setText(_translate("MainWindow", "Sửa"))
        self.btnXoa.setText(_translate("MainWindow", "Xóa"))
        self.btnLamMoi.setText(_translate("MainWindow", "Làm mới"))
        self.label_26.setText(_translate("MainWindow", "Giảng viên"))
        self.label_17.setText(_translate("MainWindow", "Hệ thống tìm kiếm:"))
        self.label_18.setText(_translate("MainWindow", "Tìm kiếm theo:"))
        self.cmbOptionFind.setItemText(0, _translate("MainWindow", "ID buổi học"))
        item = self.tbwBuoiHoc.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID buổi học"))
        item = self.tbwBuoiHoc.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Giờ bắt đầu"))
        item = self.tbwBuoiHoc.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Giờ kết thúc"))
        item = self.tbwBuoiHoc.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ngày"))
        item = self.tbwBuoiHoc.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Lớp học"))
        item = self.tbwBuoiHoc.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Giảng viên"))
        self.label_15.setText(_translate("MainWindow", "Phần mềm điểm danh sinh viên"))


    def loadDataQTable(self):

        dd = BuoiHocBUS()
        list = dd.get()
        tablerow=0
        self.tbwBuoiHoc.setRowCount(list.__len__())
             
        if list is not None:
                for row in list:
                        self.tbwBuoiHoc.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(str(row[0])))
                        self.tbwBuoiHoc.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(str(row[1])))
                        self.tbwBuoiHoc.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(str(row[2])))
                        self.tbwBuoiHoc.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(str(row[3])))
                        self.tbwBuoiHoc.setItem(tablerow, 4, QtWidgets.QTableWidgetItem(str(row[4])))
                        self.tbwBuoiHoc.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(str(row[5])))
                        tablerow+=1

    def loadDataCmbLop(self):

        bh = BuoiHocBUS()
        list = bh.getCmbLop();
        self.cmbLop.addItem("Chọn ID Lớp")
        if list is not None:
                for row in list:
                        self.cmbLop.addItem(row[0]);
    
    def loadDataCmbGv(self):

        bh = BuoiHocBUS()
        list = bh.getCmbGv();
        self.cmbGv.addItem("Chọn ID Giảng Viên")
        if list is not None:
                for row in list:
                        self.cmbGv.addItem(row[0]);
        

    def getDataRow(self):                
        cr = self.tbwBuoiHoc.currentRow()     
        self.ma = self.tbwBuoiHoc.item(cr,0).text()     
        time_str_GioBD = self.tbwBuoiHoc.item(cr,1).text()
        time_str_GioKT = self.tbwBuoiHoc.item(cr,2).text()
        date_str = self.tbwBuoiHoc.item(cr,3).text()
        time_format =  "%H:%M:%S"
        date_format = "%Y-%m-%d"
        timeGioBD = datetime.datetime.strptime(time_str_GioBD,time_format).time()
        timeGioKT = datetime.datetime.strptime(time_str_GioKT,time_format).time()
        date = datetime.datetime.strptime(date_str,date_format).date()
        self.ma = self.tbwBuoiHoc.item(cr,0).text()
        self.timeGioBD.setTime(timeGioBD)
        self.timeGioKT.setTime(timeGioKT)
        self.dateNgay.setDate(date)
        self.cmbLop.setCurrentText(self.tbwBuoiHoc.item(cr,4).text())
        self.cmbGv.setCurrentText(self.tbwBuoiHoc.item(cr,5).text())


    def update(self):
        bhBUS = BuoiHocBUS()
        mabuoihoc = self.ma
        giobatdau = self.timeGioBD.text()
        gioketthuc = self.timeGioKT.text()
        ngay = self.dateNgay.text()
        malop = self.cmbLop.currentText()
        magiangvien = self.cmbGv.currentText()

        bh = BuoiHoc(mabuoihoc, giobatdau, gioketthuc, ngay, malop, magiangvien)
        if(bhBUS.update(bh)):
                QMessageBox.information(self.centralwidget,"Thông báo","Cập nhật thành công")
                self.loadDataQTable()
        else:
                QMessageBox.information(self.centralwidget,"Thông báo","Cập nhật thất bại")

    def clear(self):
        self.timeGioBD.setTime(QtCore.QTime(7, 00, 00))
        self.timeGioKT.setTime(QtCore.QTime(17, 30, 00))
        self.dateNgay.setDate(QtCore.QDate.currentDate())
        self.cmbLop.clear()
        self.loadDataCmbLop()
        self.cmbGv.clear()
        self.loadDataCmbGv()

    def add(self):
        bhBUS = BuoiHocBUS()
        mabuoihoc = bhBUS.generateID()
        giobatdau = self.timeGioBD.text()
        gioketthuc = self.timeGioKT.text()
        ngay = self.dateNgay.text()
        malop = self.cmbLop.currentText()
        magiangvien = self.cmbGv.currentText()
                
        bh = BuoiHoc(mabuoihoc, giobatdau, gioketthuc, ngay, malop, magiangvien)
        if(bhBUS.add(bh)):
                QMessageBox.information(self.centralwidget,"Thông báo","Thêm thành công")
                self.loadDataQTable()
                self.clear()
        else:
                QMessageBox.information(self.centralwidget,"Thông báo","Thêm thất bại")

    def delete(self):
        bhBUS = BuoiHocBUS()
        if(bhBUS.delete(self.ma)):
                QMessageBox.information(self.centralwidget,"Thông báo","Xóa thành công")
                self.loadDataQTable()
                self.clear()
        else:
                QMessageBox.information(self.centralwidget,"Thông báo","Xóa thất bại")

    def find(self):
        bh = BuoiHocBUS()
        key =  self.cmbOptionFind.currentData()
        value = self.txtFind.text()
        list = bh.find(key, value)
        tablerow=0
        self.tbwBuoiHoc.setRowCount(list.__len__())
             
        if list is not None:
                for row in list:
                        self.tbwBuoiHoc.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(str(row[0])))
                        self.tbwBuoiHoc.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(str(row[1])))
                        self.tbwBuoiHoc.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(str(row[2])))
                        self.tbwBuoiHoc.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(str(row[3])))
                        self.tbwBuoiHoc.setItem(tablerow, 4, QtWidgets.QTableWidgetItem(str(row[4])))
                        self.tbwBuoiHoc.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(str(row[5])))
                        tablerow+=1

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UI_QuanLyBuoiHoc()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
