# Form implementation generated from reading ui file 'ui/ViewImage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
from PyQt6.QtGui import QPixmap
from PyQt6.QtWidgets import QApplication, QMainWindow
import os
class ViewImage(object):     
    idSV = ''
    def __init__(self , id):
        self.idSV = id
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 460)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 675, 412))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        
        # self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        # self.label.setObjectName("label")
        # self.gridLayout.addWidget(self.label)

        for i in range(200):
            # Tạo QLabel để hiển thị ảnh
            label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
            label.setFixedSize(120, 100) # đặt kích thước cho label
            label.setAlignment(Qt.AlignmentFlag.AlignCenter) # căn giữa ảnh trong label
            
            # Tạo đối tượng QPixmap từ file ảnh
            file_path = os.path.join("image\photo\\"+ self.idSV +'-image'+str(i+1)+'.jpg')
            pixmap = QPixmap(file_path)
            
            # Thay đổi kích thước của ảnh
            scaled_pixmap = pixmap.scaled(label.size(), Qt.AspectRatioMode.KeepAspectRatio, Qt.TransformationMode.SmoothTransformation)
            # Đặt ảnh vào QLabel
            label.setPixmap(scaled_pixmap)
            
            # Đặt QLabel vào ô tương ứng trong lưới
            row = i // 5 # mỗi hàng có 5 ảnh
            col = i % 5
            self.gridLayout.addWidget(label, row, col)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = ViewImage('SV003')
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
