# Form implementation generated from reading ui file 'c:\Users\Duyen\OneDrive\Documents\github\ProjectPython-FaceID\ui\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menu_widget = QCustomSlideMenu(parent=self.centralwidget)
        self.menu_widget.setGeometry(QtCore.QRect(-1, 99, 171, 481))
        self.menu_widget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.menu_widget.setStyleSheet("#frmMenu\n"
"{\n"
"    border-width: 0.1;\n"
"    border-radius: 5;\n"
"     border-style: solid;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 92, 151, 255), stop:0.994318 rgba(54, 55, 149, 255));\n"
"}")
        self.menu_widget.setObjectName("menu_widget")
        self.verticalFrame_3 = QtWidgets.QFrame(parent=self.menu_widget)
        self.verticalFrame_3.setGeometry(QtCore.QRect(8, 38, 161, 267))
        self.verticalFrame_3.setObjectName("verticalFrame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_6.setSpacing(15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btnTrangChu_3 = QtWidgets.QPushButton(parent=self.verticalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTrangChu_3.sizePolicy().hasHeightForWidth())
        self.btnTrangChu_3.setSizePolicy(sizePolicy)
        self.btnTrangChu_3.setMinimumSize(QtCore.QSize(0, 30))
        self.btnTrangChu_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnTrangChu_3.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnTrangChu_3.setFont(font)
        self.btnTrangChu_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnTrangChu_3.setStyleSheet("#btnTrangChu\n"
"{\n"
"    font-weight:bold;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Duyen\\OneDrive\\Documents\\github\\ProjectPython-FaceID\\ui\\../image/icon/home_40px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnTrangChu_3.setIcon(icon)
        self.btnTrangChu_3.setIconSize(QtCore.QSize(15, 15))
        self.btnTrangChu_3.setObjectName("btnTrangChu_3")
        self.verticalLayout_6.addWidget(self.btnTrangChu_3)
        self.btnQuanLy_3 = QtWidgets.QPushButton(parent=self.verticalFrame_3)
        self.btnQuanLy_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnQuanLy_3.setFont(font)
        self.btnQuanLy_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnQuanLy_3.setStyleSheet("#btnQuanLy\n"
"{\n"
"    font-weight:bold;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Duyen\\OneDrive\\Documents\\github\\ProjectPython-FaceID\\ui\\../image/icon/document_40px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnQuanLy_3.setIcon(icon1)
        self.btnQuanLy_3.setIconSize(QtCore.QSize(15, 15))
        self.btnQuanLy_3.setObjectName("btnQuanLy_3")
        self.verticalLayout_6.addWidget(self.btnQuanLy_3)
        self.btnNhanDien_3 = QtWidgets.QPushButton(parent=self.verticalFrame_3)
        self.btnNhanDien_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnNhanDien_3.setFont(font)
        self.btnNhanDien_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnNhanDien_3.setStyleSheet("#btnNhanDien\n"
"{\n"
"    font-weight:bold;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\Duyen\\OneDrive\\Documents\\github\\ProjectPython-FaceID\\ui\\../image/icon/client_management_40px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnNhanDien_3.setIcon(icon2)
        self.btnNhanDien_3.setIconSize(QtCore.QSize(20, 20))
        self.btnNhanDien_3.setObjectName("btnNhanDien_3")
        self.verticalLayout_6.addWidget(self.btnNhanDien_3)
        self.btnThongKe_3 = QtWidgets.QPushButton(parent=self.verticalFrame_3)
        self.btnThongKe_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnThongKe_3.setFont(font)
        self.btnThongKe_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnThongKe_3.setStyleSheet("#btnThongKe\n"
"{\n"
"    font-weight:bold;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\Duyen\\OneDrive\\Documents\\github\\ProjectPython-FaceID\\ui\\../image/icon/graph_report_script_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnThongKe_3.setIcon(icon3)
        self.btnThongKe_3.setIconSize(QtCore.QSize(20, 20))
        self.btnThongKe_3.setObjectName("btnThongKe_3")
        self.verticalLayout_6.addWidget(self.btnThongKe_3)
        self.btnMatKhau_3 = QtWidgets.QPushButton(parent=self.verticalFrame_3)
        self.btnMatKhau_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnMatKhau_3.setFont(font)
        self.btnMatKhau_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnMatKhau_3.setStyleSheet("#btnMatKhau\n"
"{\n"
"    font-weight:bold;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\Duyen\\OneDrive\\Documents\\github\\ProjectPython-FaceID\\ui\\../image/icon/password_40px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnMatKhau_3.setIcon(icon4)
        self.btnMatKhau_3.setIconSize(QtCore.QSize(20, 20))
        self.btnMatKhau_3.setObjectName("btnMatKhau_3")
        self.verticalLayout_6.addWidget(self.btnMatKhau_3)
        self.btnLogout_3 = QtWidgets.QPushButton(parent=self.verticalFrame_3)
        self.btnLogout_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnLogout_3.setFont(font)
        self.btnLogout_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnLogout_3.setStyleSheet("#btnLogout\n"
"{\n"
"    font-weight:bold;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("c:\\Users\\Duyen\\OneDrive\\Documents\\github\\ProjectPython-FaceID\\ui\\../image/icon/logout_40px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnLogout_3.setIcon(icon5)
        self.btnLogout_3.setIconSize(QtCore.QSize(20, 20))
        self.btnLogout_3.setObjectName("btnLogout_3")
        self.verticalLayout_6.addWidget(self.btnLogout_3)
        self.btnMenu = QtWidgets.QPushButton(parent=self.menu_widget)
        self.btnMenu.setGeometry(QtCore.QRect(130, 10, 30, 26))
        self.btnMenu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnMenu.setStyleSheet("#btnTime\n"
"{\n"
"background-color: transparent;\n"
"}")
        self.btnMenu.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("c:\\Users\\Duyen\\OneDrive\\Documents\\github\\ProjectPython-FaceID\\ui\\../image/icon/menu_rounded_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnMenu.setIcon(icon6)
        self.btnMenu.setIconSize(QtCore.QSize(20, 20))
        self.btnMenu.setObjectName("btnMenu")
        self.frmHeader = QtWidgets.QFrame(parent=self.centralwidget)
        self.frmHeader.setGeometry(QtCore.QRect(0, 30, 851, 51))
        self.frmHeader.setAccessibleName("")
        self.frmHeader.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frmHeader.setStyleSheet("#frmHeader{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 92, 151, 255), stop:0.994318 rgba(54, 55, 149, 255));\n"
"}")
        self.frmHeader.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frmHeader.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frmHeader.setLineWidth(1)
        self.frmHeader.setObjectName("frmHeader")
        self.label_8 = QtWidgets.QLabel(parent=self.frmHeader)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 801, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("#label_3\n"
"{\n"
"    font-weight:bold;\n"
"background-color: transparent;\n"
"}")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.frmHeader)
        self.label_9.setGeometry(QtCore.QRect(50, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.NoAntialias)
        self.label_9.setFont(font)
        self.label_9.setAcceptDrops(False)
        self.label_9.setToolTip("")
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("#label_2\n"
"{\n"
"background-color: transparent;\n"
"}")
        self.label_9.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_9.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_9.setScaledContents(False)
        self.label_9.setWordWrap(False)
        self.label_9.setIndent(-1)
        self.label_9.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.frmHeader)
        self.label_10.setGeometry(QtCore.QRect(50, 30, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("#label_4\n"
"{\n"
"background-color: transparent;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.btnDark_3 = QtWidgets.QPushButton(parent=self.frmHeader)
        self.btnDark_3.setGeometry(QtCore.QRect(764, 10, 31, 31))
        self.btnDark_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnDark_3.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("c:\\Users\\Duyen\\OneDrive\\Documents\\github\\ProjectPython-FaceID\\ui\\../image/icon/moon_symbol_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnDark_3.setIcon(icon7)
        self.btnDark_3.setIconSize(QtCore.QSize(20, 20))
        self.btnDark_3.setObjectName("btnDark_3")
        self.btnTime_3 = QtWidgets.QPushButton(parent=self.frmHeader)
        self.btnTime_3.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.btnTime_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnTime_3.setStyleSheet("#btnTime\n"
"{\n"
"background-color: transparent;\n"
"}")
        self.btnTime_3.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("c:\\Users\\Duyen\\OneDrive\\Documents\\github\\ProjectPython-FaceID\\ui\\../image/icon/time_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnTime_3.setIcon(icon8)
        self.btnTime_3.setIconSize(QtCore.QSize(20, 20))
        self.btnTime_3.setObjectName("btnTime_3")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, 0, 801, 31))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.btnClose_3 = QtWidgets.QPushButton(parent=self.frame)
        self.btnClose_3.setGeometry(QtCore.QRect(777, 4, 24, 24))
        self.btnClose_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnClose_3.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("c:\\Users\\Duyen\\OneDrive\\Documents\\github\\ProjectPython-FaceID\\ui\\../image/icon/close_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnClose_3.setIcon(icon9)
        self.btnClose_3.setIconSize(QtCore.QSize(20, 20))
        self.btnClose_3.setObjectName("btnClose_3")
        self.btnMinimize_3 = QtWidgets.QPushButton(parent=self.frame)
        self.btnMinimize_3.setGeometry(QtCore.QRect(752, 4, 24, 24))
        self.btnMinimize_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnMinimize_3.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("c:\\Users\\Duyen\\OneDrive\\Documents\\github\\ProjectPython-FaceID\\ui\\../image/icon/subtract_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnMinimize_3.setIcon(icon10)
        self.btnMinimize_3.setIconSize(QtCore.QSize(20, 20))
        self.btnMinimize_3.setObjectName("btnMinimize_3")
        self.label_17 = QtWidgets.QLabel(parent=self.frame)
        self.label_17.setGeometry(QtCore.QRect(10, 2, 201, 26))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.NoAntialias)
        self.label_17.setFont(font)
        self.label_17.setAcceptDrops(False)
        self.label_17.setToolTip("")
        self.label_17.setAutoFillBackground(False)
        self.label_17.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_17.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_17.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_17.setScaledContents(False)
        self.label_17.setWordWrap(False)
        self.label_17.setIndent(-1)
        self.label_17.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_17.setObjectName("label_17")
        self.frmMain = QtWidgets.QFrame(parent=self.centralwidget)
        self.frmMain.setGeometry(QtCore.QRect(190, 100, 591, 481))
        self.frmMain.setStyleSheet("#frmMain\n"
"{\n"
"    border-width: 2;\n"
"    border-radius: 5;\n"
"     border-style: solid;\n"
"      border-color: #457fca;\n"
"}")
        self.frmMain.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frmMain.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frmMain.setLineWidth(2)
        self.frmMain.setObjectName("frmMain")
        self.frmHome1_3 = QtWidgets.QFrame(parent=self.frmMain)
        self.frmHome1_3.setGeometry(QtCore.QRect(40, 40, 241, 161))
        self.frmHome1_3.setStyleSheet("#frmHome1{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"")
        self.frmHome1_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frmHome1_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frmHome1_3.setObjectName("frmHome1_3")
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.frmHome1_3)
        self.pushButton_12.setGeometry(QtCore.QRect(0, 40, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setAutoFillBackground(False)
        self.pushButton_12.setStyleSheet("#pushButton_6\n"
"{\n"
"border:none;\n"
"font-weight:bold;\n"
"background-color: transparent;\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("c:\\Users\\Duyen\\OneDrive\\Documents\\github\\ProjectPython-FaceID\\ui\\../image/icon/student_center_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_12.setIcon(icon11)
        self.pushButton_12.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_12.setObjectName("pushButton_12")
        self.lblSV_3 = QtWidgets.QLabel(parent=self.frmHome1_3)
        self.lblSV_3.setGeometry(QtCore.QRect(0, 90, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.lblSV_3.setFont(font)
        self.lblSV_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lblSV_3.setStyleSheet("#lblSV\n"
"{\n"
"color:white;\n"
"font-weight:bold;\n"
"background-color: transparent;\n"
"}")
        self.lblSV_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSV_3.setObjectName("lblSV_3")
        self.btnUpdateSV_3 = QtWidgets.QPushButton(parent=self.frmHome1_3)
        self.btnUpdateSV_3.setGeometry(QtCore.QRect(10, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnUpdateSV_3.setFont(font)
        self.btnUpdateSV_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnUpdateSV_3.setStyleSheet("#btnUpdateSV\n"
"{\n"
"border-radius: 5px;\n"
"background-color: white;\n"
"font-weight: bold;\n"
"color:black;\n"
"}\n"
"")
        self.btnUpdateSV_3.setObjectName("btnUpdateSV_3")
        self.frmHome2_3 = QtWidgets.QFrame(parent=self.frmMain)
        self.frmHome2_3.setGeometry(QtCore.QRect(330, 40, 241, 161))
        self.frmHome2_3.setStyleSheet("#frmHome2{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"")
        self.frmHome2_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frmHome2_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frmHome2_3.setObjectName("frmHome2_3")
        self.btnUpdateClass_3 = QtWidgets.QPushButton(parent=self.frmHome2_3)
        self.btnUpdateClass_3.setGeometry(QtCore.QRect(10, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnUpdateClass_3.setFont(font)
        self.btnUpdateClass_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnUpdateClass_3.setStyleSheet("#btnUpdateClass\n"
"{\n"
" border-radius: 5px;\n"
"background-color: white;\n"
"font-weight:bold;\n"
"color:black;\n"
"}")
        self.btnUpdateClass_3.setObjectName("btnUpdateClass_3")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.frmHome2_3)
        self.pushButton_13.setGeometry(QtCore.QRect(0, 40, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("#pushButton_7\n"
"{\n"
"border:none;\n"
"font-weight:bold;\n"
"background-color: transparent;\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("c:\\Users\\Duyen\\OneDrive\\Documents\\github\\ProjectPython-FaceID\\ui\\../image/icon/google_classroom_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_13.setIcon(icon12)
        self.pushButton_13.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_13.setObjectName("pushButton_13")
        self.lblBuoiHoc_3 = QtWidgets.QLabel(parent=self.frmHome2_3)
        self.lblBuoiHoc_3.setGeometry(QtCore.QRect(0, 90, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.lblBuoiHoc_3.setFont(font)
        self.lblBuoiHoc_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lblBuoiHoc_3.setStyleSheet("#lblBuoiHoc\n"
"{\n"
"color:white;\n"
"font-weight:bold;\n"
"background-color: transparent;\n"
"}")
        self.lblBuoiHoc_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblBuoiHoc_3.setObjectName("lblBuoiHoc_3")
        self.frmHome3_3 = QtWidgets.QFrame(parent=self.frmMain)
        self.frmHome3_3.setGeometry(QtCore.QRect(190, 230, 241, 161))
        self.frmHome3_3.setStyleSheet("#frmHome3{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"")
        self.frmHome3_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frmHome3_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frmHome3_3.setObjectName("frmHome3_3")
        self.btnCloseCam_3 = QtWidgets.QPushButton(parent=self.frmHome3_3)
        self.btnCloseCam_3.setGeometry(QtCore.QRect(10, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnCloseCam_3.setFont(font)
        self.btnCloseCam_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCloseCam_3.setStyleSheet("#btnCloseCam\n"
"{\n"
" border-radius: 5px;\n"
"background-color: white;\n"
"font-weight:bold;\n"
"color:black;\n"
"}")
        self.btnCloseCam_3.setObjectName("btnCloseCam_3")
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.frmHome3_3)
        self.pushButton_14.setGeometry(QtCore.QRect(0, 40, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("#pushButton_8\n"
"{\n"
"border:none;\n"
"font-weight:bold;\n"
"background-color: transparent;\n"
"}")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("c:\\Users\\Duyen\\OneDrive\\Documents\\github\\ProjectPython-FaceID\\ui\\../image/icon/camera_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_14.setIcon(icon13)
        self.pushButton_14.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_14.setObjectName("pushButton_14")
        self.lblStatusCam_3 = QtWidgets.QLabel(parent=self.frmHome3_3)
        self.lblStatusCam_3.setGeometry(QtCore.QRect(0, 90, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.lblStatusCam_3.setFont(font)
        self.lblStatusCam_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lblStatusCam_3.setStyleSheet("#lblStatusCam\n"
"{\n"
"color:white;\n"
"font-weight:bold;\n"
"background-color: transparent;\n"
"}")
        self.lblStatusCam_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblStatusCam_3.setObjectName("lblStatusCam_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnTrangChu_3.setText(_translate("MainWindow", "Trang chủ"))
        self.btnQuanLy_3.setText(_translate("MainWindow", "Quản lý"))
        self.btnNhanDien_3.setText(_translate("MainWindow", "Nhận diện"))
        self.btnThongKe_3.setText(_translate("MainWindow", "Thống kê"))
        self.btnMatKhau_3.setText(_translate("MainWindow", "Mật khẩu"))
        self.btnLogout_3.setText(_translate("MainWindow", "Đăng xuất"))
        self.label_8.setText(_translate("MainWindow", "HỆ THỐNG ĐIỂM DANH BẰNG NHẬN DIỆN KHUÔN MẶT"))
        self.label_9.setText(_translate("MainWindow", "09:15:00"))
        self.label_10.setText(_translate("MainWindow", "02/02/2022"))
        self.label_17.setText(_translate("MainWindow", "Phần mềm điểm danh sinh viên"))
        self.pushButton_12.setText(_translate("MainWindow", " Số sinh viên quản lý"))
        self.lblSV_3.setText(_translate("MainWindow", "20"))
        self.btnUpdateSV_3.setText(_translate("MainWindow", "Cập nhật"))
        self.btnUpdateClass_3.setText(_translate("MainWindow", "Cập nhật"))
        self.pushButton_13.setText(_translate("MainWindow", "Buổi học đang diễn ra"))
        self.lblBuoiHoc_3.setText(_translate("MainWindow", "10"))
        self.btnCloseCam_3.setText(_translate("MainWindow", "Đóng"))
        self.pushButton_14.setText(_translate("MainWindow", "Trạng thái nhận diện"))
        self.lblStatusCam_3.setText(_translate("MainWindow", "Mở"))
from qcustomslidemenu import QCustomSlideMenu
