# Form implementation generated from reading ui file 'c:\Users\thuyn\Documents\GitHub\ProjectPython-FaceID\ui\NhanDien.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 590)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frmHeader = QtWidgets.QFrame(parent=self.centralwidget)
        self.frmHeader.setGeometry(QtCore.QRect(0, 30, 851, 51))
        self.frmHeader.setAccessibleName("")
        self.frmHeader.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frmHeader.setStyleSheet("#frmHeader{background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255))}\n"
"")
        self.frmHeader.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frmHeader.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frmHeader.setLineWidth(1)
        self.frmHeader.setObjectName("frmHeader")
        self.label_3 = QtWidgets.QLabel(parent=self.frmHeader)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 801, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("#label_3\n"
"{\n"
"    font-weight:bold;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btnBack = QtWidgets.QPushButton(parent=self.frmHeader)
        self.btnBack.setGeometry(QtCore.QRect(730, 12, 61, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnBack.setFont(font)
        self.btnBack.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnBack.setStyleSheet("#btnLogout\n"
"{\n"
"    padding:3px;\n"
"}")
        self.btnBack.setObjectName("btnBack")
        self.label_2 = QtWidgets.QLabel(parent=self.frmHeader)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.NoAntialias)
        self.label_2.setFont(font)
        self.label_2.setAcceptDrops(False)
        self.label_2.setToolTip("")
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setIndent(-1)
        self.label_2.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.frmHeader)
        self.label_4.setGeometry(QtCore.QRect(50, 30, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnDark = QtWidgets.QPushButton(parent=self.frmHeader)
        self.btnDark.setGeometry(QtCore.QRect(680, 8, 31, 31))
        self.btnDark.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnDark.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\thuyn\\Documents\\GitHub\\ProjectPython-FaceID\\ui\\../image/icon/moon_symbol_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnDark.setIcon(icon)
        self.btnDark.setIconSize(QtCore.QSize(20, 20))
        self.btnDark.setObjectName("btnDark")
        self.btnTime = QtWidgets.QPushButton(parent=self.frmHeader)
        self.btnTime.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.btnTime.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnTime.setStyleSheet("#btnTime\n"
"{\n"
"background-color: transparent;\n"
"}")
        self.btnTime.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\thuyn\\Documents\\GitHub\\ProjectPython-FaceID\\ui\\../image/icon/time_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnTime.setIcon(icon1)
        self.btnTime.setIconSize(QtCore.QSize(20, 20))
        self.btnTime.setObjectName("btnTime")
        self.label_3.raise_()
        self.btnBack.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.btnDark.raise_()
        self.btnTime.raise_()
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 100, 441, 421))
        self.frame.setStyleSheet("#frame\n"
"{\n"
"    border-width: 2;\n"
"    border-radius: 5;\n"
"     border-style: solid;\n"
"      border-color: #457fca;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 101, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.cmbBuoiHoc = QtWidgets.QComboBox(parent=self.frame)
        self.cmbBuoiHoc.setGeometry(QtCore.QRect(120, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmbBuoiHoc.setFont(font)
        self.cmbBuoiHoc.setObjectName("cmbBuoiHoc")
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        self.label_7.setGeometry(QtCore.QRect(240, 40, 131, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.cmbLoaiDiemDanh = QtWidgets.QComboBox(parent=self.frame)
        self.cmbLoaiDiemDanh.setGeometry(QtCore.QRect(370, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmbLoaiDiemDanh.setFont(font)
        self.cmbLoaiDiemDanh.setObjectName("cmbLoaiDiemDanh")
        self.cmbLoaiDiemDanh.addItem("")
        self.cmbLoaiDiemDanh.addItem("")
        self.frmNhanDien = QtWidgets.QFrame(parent=self.frame)
        self.frmNhanDien.setGeometry(QtCore.QRect(20, 80, 401, 291))
        self.frmNhanDien.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frmNhanDien.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frmNhanDien.setObjectName("frmNhanDien")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame)
        self.frame_5.setGeometry(QtCore.QRect(20, 380, 401, 31))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.lblThongBao = QtWidgets.QLabel(parent=self.frame_5)
        self.lblThongBao.setGeometry(QtCore.QRect(10, 5, 381, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblThongBao.setFont(font)
        self.lblThongBao.setStyleSheet("#lblThongBao\n"
"{\n"
"color:red;\n"
"}")
        self.lblThongBao.setObjectName("lblThongBao")
        self.label_20 = QtWidgets.QLabel(parent=self.frame)
        self.label_20.setGeometry(QtCore.QRect(20, 10, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("#label_20\n"
"{\n"
"font-weight:bold;\n"
"}")
        self.label_20.setObjectName("label_20")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(480, 100, 301, 301))
        self.frame_2.setStyleSheet("#frame_2\n"
"{\n"
"    border-width: 2;\n"
"    border-radius: 5;\n"
"     border-style: solid;\n"
"      border-color: #457fca;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("#label_9\n"
"{\n"
"font-weight:bold;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.frmAnhSV = QtWidgets.QFrame(parent=self.frame_2)
        self.frmAnhSV.setGeometry(QtCore.QRect(89, 40, 151, 121))
        self.frmAnhSV.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frmAnhSV.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frmAnhSV.setObjectName("frmAnhSV")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(50, 180, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.txtMaSV = QtWidgets.QLineEdit(parent=self.frame_2)
        self.txtMaSV.setGeometry(QtCore.QRect(130, 180, 141, 20))
        self.txtMaSV.setObjectName("txtMaSV")
        self.txtHoTen = QtWidgets.QLineEdit(parent=self.frame_2)
        self.txtHoTen.setGeometry(QtCore.QRect(130, 220, 141, 20))
        self.txtHoTen.setText("")
        self.txtHoTen.setObjectName("txtHoTen")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(50, 220, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(50, 260, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.timeThoiGian = QtWidgets.QTimeEdit(parent=self.frame_2)
        self.timeThoiGian.setGeometry(QtCore.QRect(130, 260, 141, 22))
        self.timeThoiGian.setObjectName("timeThoiGian")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(480, 420, 301, 151))
        self.frame_3.setStyleSheet("#frame_3\n"
"{\n"
"    border-width: 2;\n"
"    border-radius: 5;\n"
"     border-style: solid;\n"
"      border-color: #457fca;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_13 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(20, 20, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("#label_13\n"
"{\n"
"font-weight:bold;\n"
"}")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(30, 80, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(30, 110, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_16.setGeometry(QtCore.QRect(30, 50, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lblLop = QtWidgets.QLabel(parent=self.frame_3)
        self.lblLop.setGeometry(QtCore.QRect(130, 50, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblLop.setFont(font)
        self.lblLop.setStyleSheet("#lblLop\n"
"{\n"
"color:red;\n"
"}")
        self.lblLop.setObjectName("lblLop")
        self.lblIDBuoiHoc = QtWidgets.QLabel(parent=self.frame_3)
        self.lblIDBuoiHoc.setGeometry(QtCore.QRect(130, 80, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblIDBuoiHoc.setFont(font)
        self.lblIDBuoiHoc.setStyleSheet("#lblIDBuoiHoc{\n"
"color:red;\n"
"}")
        self.lblIDBuoiHoc.setObjectName("lblIDBuoiHoc")
        self.lblThoiGian = QtWidgets.QLabel(parent=self.frame_3)
        self.lblThoiGian.setGeometry(QtCore.QRect(130, 110, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblThoiGian.setFont(font)
        self.lblThoiGian.setStyleSheet("#lblThoiGian\n"
"{\n"
"color:red;\n"
"}")
        self.lblThoiGian.setObjectName("lblThoiGian")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 530, 441, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnMoCam = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnMoCam.setFont(font)
        self.btnMoCam.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnMoCam.setStyleSheet("#btnMoCam{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"color:white;\n"
"font-weight:bold;\n"
"border-radius:3px;\n"
"padding: 7px;\n"
"}\n"
"#btnMoCam:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"}")
        self.btnMoCam.setObjectName("btnMoCam")
        self.horizontalLayout.addWidget(self.btnMoCam)
        self.btnDongCam = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnDongCam.setFont(font)
        self.btnDongCam.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnDongCam.setStyleSheet("#btnDongCam{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 127, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"color:white;\n"
"font-weight:bold;\n"
"border-radius:3px;\n"
"padding: 7px;\n"
"}\n"
"#btnDongCam:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(107, 149, 202, 255), stop:1 rgba(86, 145, 200, 255));\n"
"}")
        self.btnDongCam.setObjectName("btnDongCam")
        self.horizontalLayout.addWidget(self.btnDongCam)
        self.frame_7 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 801, 31))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.btnClose = QtWidgets.QPushButton(parent=self.frame_7)
        self.btnClose.setGeometry(QtCore.QRect(777, 4, 24, 24))
        self.btnClose.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnClose.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\thuyn\\Documents\\GitHub\\ProjectPython-FaceID\\ui\\../image/icon/close_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnClose.setIcon(icon2)
        self.btnClose.setIconSize(QtCore.QSize(20, 20))
        self.btnClose.setObjectName("btnClose")
        self.btnMinimize = QtWidgets.QPushButton(parent=self.frame_7)
        self.btnMinimize.setGeometry(QtCore.QRect(752, 4, 24, 24))
        self.btnMinimize.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnMinimize.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\thuyn\\Documents\\GitHub\\ProjectPython-FaceID\\ui\\../image/icon/subtract_50px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnMinimize.setIcon(icon3)
        self.btnMinimize.setIconSize(QtCore.QSize(20, 20))
        self.btnMinimize.setObjectName("btnMinimize")
        self.label_21 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_21.setGeometry(QtCore.QRect(10, 2, 201, 26))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.NoAntialias)
        self.label_21.setFont(font)
        self.label_21.setAcceptDrops(False)
        self.label_21.setToolTip("")
        self.label_21.setAutoFillBackground(False)
        self.label_21.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_21.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_21.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_21.setScaledContents(False)
        self.label_21.setWordWrap(False)
        self.label_21.setIndent(-1)
        self.label_21.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_21.setObjectName("label_21")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Nhận diện khuôn mặt"))
        self.btnBack.setText(_translate("MainWindow", "Trở về"))
        self.label_2.setText(_translate("MainWindow", "09:15:00"))
        self.label_4.setText(_translate("MainWindow", "02/02/2022"))
        self.label_6.setText(_translate("MainWindow", "Chọn buổi học:"))
        self.label_7.setText(_translate("MainWindow", "Chọn loại điểm danh"))
        self.cmbLoaiDiemDanh.setItemText(0, _translate("MainWindow", "Vào"))
        self.cmbLoaiDiemDanh.setItemText(1, _translate("MainWindow", "Ra"))
        self.lblThongBao.setText(_translate("MainWindow", "Thông báo: Vui lòng chọn ID buổi học để mở camera điểm danh!"))
        self.label_20.setText(_translate("MainWindow", "Màn hình nhận diện"))
        self.label_9.setText(_translate("MainWindow", "Thông tin điểm danh"))
        self.label_10.setText(_translate("MainWindow", "Mã SV:"))
        self.label_11.setText(_translate("MainWindow", "Họ tên:"))
        self.label_12.setText(_translate("MainWindow", "Thời gian:"))
        self.label_13.setText(_translate("MainWindow", "Thông tin buổi học"))
        self.label_14.setText(_translate("MainWindow", "ID buổi học:"))
        self.label_15.setText(_translate("MainWindow", "Thời gian:"))
        self.label_16.setText(_translate("MainWindow", "Lớp:"))
        self.lblLop.setText(_translate("MainWindow", "DCT1200"))
        self.lblIDBuoiHoc.setText(_translate("MainWindow", "2"))
        self.lblThoiGian.setText(_translate("MainWindow", "7:00:00 - 11:00:00"))
        self.btnMoCam.setText(_translate("MainWindow", "Mở Camera"))
        self.btnDongCam.setText(_translate("MainWindow", "Đóng Camera"))
        self.label_21.setText(_translate("MainWindow", "Phần mềm điểm danh sinh viên"))
